/*
 * Verify script for sample-audit-violations integration test.
 * This project tests HexaGlue without JPA plugin (no generated sources for JPA).
 */

def buildLog = new File(basedir, "build.log")
assert buildLog.exists() : "build.log should exist"

def logContent = buildLog.text

// Verify build success (violations configured not to fail build)
assert !logContent.contains("BUILD FAILURE") : "Build should not fail"

// Verify HexaGlue plugin executed
assert logContent.contains("HexaGlue analyzing:") :
    "Should contain HexaGlue analyzing output"

// Verify classification completed
assert logContent.contains("Classification complete:") :
    "Should contain 'Classification complete:'"

// Check living-doc directory (generated by living-doc plugin)
def livingDocDir = new File(basedir, "target/hexaglue/reports/living-doc")
assert livingDocDir.exists() :
    "Living documentation directory should exist"

// Verify living-doc plugin ran
assert logContent.contains("io.hexaglue.plugin.livingdoc") :
    "Build log should contain living-doc plugin execution"

println 'SUCCESS: sample-audit-violations integration test passed'
return true
