/*
 * This Source Code Form is part of the HexaGlue project.
 * Copyright (c) 2026 Scalastic
 *
 * This Source Code Form is subject to the terms of the Mozilla Public
 * License, v. 2.0. If a copy of the MPL was not distributed with this
 * file, You can obtain one at https://mozilla.org/MPL/2.0/.
 *
 * Commercial licensing options are available for organizations wishing
 * to use HexaGlue under terms different from the MPL 2.0.
 * Contact: info@hexaglue.io
 */

package io.hexaglue.plugin.livingdoc.markdown;

/**
 * Fluent API for building Markdown documents.
 *
 * <p>Provides a type-safe, composable way to generate Markdown content with support for:
 * <ul>
 *   <li>Headers (h1-h4)</li>
 *   <li>Text formatting (bold, italic, code)</li>
 *   <li>Links</li>
 *   <li>Lists (bullet and numbered)</li>
 *   <li>Tables (via nested {@link TableBuilder})</li>
 *   <li>Collapsible sections (via nested {@link CollapsibleBuilder})</li>
 *   <li>Horizontal rules</li>
 *   <li>Blockquotes</li>
 * </ul>
 *
 * <p>Example usage:
 * <pre>{@code
 * String doc = new MarkdownBuilder()
 *     .h1("Architecture Overview")
 *     .paragraph("Generated by HexaGlue")
 *     .horizontalRule()
 *     .h2("Summary")
 *     .table("Metric", "Count")
 *         .row("Aggregates", "3")
 *         .row("Entities", "5")
 *         .end()
 *     .build();
 * }</pre>
 *
 * @since 0.1.0
 */
public final class MarkdownBuilder {

    private final StringBuilder content;

    /**
     * Creates a new empty Markdown builder.
     */
    public MarkdownBuilder() {
        this.content = new StringBuilder();
    }

    /**
     * Internal constructor for nested builders.
     *
     * @param content the shared StringBuilder to append to
     */
    MarkdownBuilder(StringBuilder content) {
        this.content = content;
    }

    /**
     * Adds a level 1 header.
     *
     * @param text the header text
     * @return this builder for method chaining
     */
    public MarkdownBuilder h1(String text) {
        content.append("# ").append(text).append("\n\n");
        return this;
    }

    /**
     * Adds a level 2 header.
     *
     * @param text the header text
     * @return this builder for method chaining
     */
    public MarkdownBuilder h2(String text) {
        content.append("## ").append(text).append("\n\n");
        return this;
    }

    /**
     * Adds a level 3 header.
     *
     * @param text the header text
     * @return this builder for method chaining
     */
    public MarkdownBuilder h3(String text) {
        content.append("### ").append(text).append("\n\n");
        return this;
    }

    /**
     * Adds a level 4 header.
     *
     * @param text the header text
     * @return this builder for method chaining
     */
    public MarkdownBuilder h4(String text) {
        content.append("#### ").append(text).append("\n\n");
        return this;
    }

    /**
     * Adds a paragraph of text followed by a blank line.
     *
     * @param text the paragraph text
     * @return this builder for method chaining
     */
    public MarkdownBuilder paragraph(String text) {
        content.append(text).append("\n\n");
        return this;
    }

    /**
     * Adds text without a trailing blank line.
     *
     * @param text the text to add
     * @return this builder for method chaining
     */
    public MarkdownBuilder text(String text) {
        content.append(text);
        return this;
    }

    /**
     * Adds a single newline character.
     *
     * @return this builder for method chaining
     */
    public MarkdownBuilder newline() {
        content.append("\n");
        return this;
    }

    /**
     * Wraps text in bold formatting.
     *
     * @param text the text to make bold
     * @return this builder for method chaining
     */
    public MarkdownBuilder bold(String text) {
        content.append("**").append(text).append("**");
        return this;
    }

    /**
     * Wraps text in italic formatting.
     *
     * @param text the text to make italic
     * @return this builder for method chaining
     */
    public MarkdownBuilder italic(String text) {
        content.append("*").append(text).append("*");
        return this;
    }

    /**
     * Wraps text in inline code formatting.
     *
     * @param text the code text
     * @return this builder for method chaining
     */
    public MarkdownBuilder code(String text) {
        content.append("`").append(text).append("`");
        return this;
    }

    /**
     * Adds a Markdown link.
     *
     * @param linkText the visible link text
     * @param url the URL to link to
     * @return this builder for method chaining
     */
    public MarkdownBuilder link(String linkText, String url) {
        content.append("[").append(linkText).append("](").append(url).append(")");
        return this;
    }

    /**
     * Adds a bullet list item.
     *
     * @param item the list item text
     * @return this builder for method chaining
     */
    public MarkdownBuilder bulletItem(String item) {
        content.append("- ").append(item).append("\n");
        return this;
    }

    /**
     * Adds a numbered list item.
     *
     * @param number the item number (e.g., 1, 2, 3)
     * @param item the list item text
     * @return this builder for method chaining
     */
    public MarkdownBuilder numberedItem(int number, String item) {
        content.append(number).append(". ").append(item).append("\n");
        return this;
    }

    /**
     * Adds a horizontal rule (---).
     *
     * @return this builder for method chaining
     */
    public MarkdownBuilder horizontalRule() {
        content.append("---\n\n");
        return this;
    }

    /**
     * Adds a blockquote.
     *
     * @param text the quoted text
     * @return this builder for method chaining
     */
    public MarkdownBuilder blockquote(String text) {
        content.append("> ").append(text).append("\n\n");
        return this;
    }

    /**
     * Starts building a table with the specified column headers.
     *
     * <p>Returns a {@link TableBuilder} that allows adding rows and eventually
     * returning back to this builder with {@link TableBuilder#end()}.
     *
     * @param headers the column headers (varargs)
     * @return a TableBuilder for adding rows
     */
    public TableBuilder table(String... headers) {
        return new TableBuilder(this, headers);
    }

    /**
     * Starts building a collapsible section (HTML details/summary).
     *
     * <p>Returns a {@link CollapsibleBuilder} that allows setting the summary
     * and content, eventually returning back to this builder with
     * {@link CollapsibleBuilder#end()}.
     *
     * @param summary the clickable summary text
     * @return a CollapsibleBuilder for adding content
     */
    public CollapsibleBuilder collapsible(String summary) {
        return new CollapsibleBuilder(this, summary);
    }

    /**
     * Appends raw content directly to the builder.
     *
     * <p>Use this when you need to add pre-generated content or
     * content not covered by the other builder methods.
     *
     * @param rawContent the raw content to append
     * @return this builder for method chaining
     */
    public MarkdownBuilder raw(String rawContent) {
        content.append(rawContent);
        return this;
    }

    /**
     * Builds and returns the complete Markdown document.
     *
     * @return the generated Markdown as a String
     */
    public String build() {
        return content.toString();
    }

    /**
     * Returns the underlying StringBuilder for nested builder access.
     *
     * @return the shared StringBuilder
     */
    StringBuilder getContent() {
        return content;
    }
}
