/*
 * This Source Code Form is part of the HexaGlue project.
 * Copyright (c) 2026 Scalastic
 *
 * This Source Code Form is subject to the terms of the Mozilla Public
 * License, v. 2.0. If a copy of the MPL was not distributed with this
 * file, You can obtain one at https://mozilla.org/MPL/2.0/.
 *
 * Commercial licensing options are available for organizations wishing
 * to use HexaGlue under terms different from the MPL 2.0.
 * Contact: info@hexaglue.io
 */

package io.hexaglue.plugin.jpa.model;

import static org.assertj.core.api.Assertions.assertThat;

import io.hexaglue.spi.ir.Identity;
import io.hexaglue.spi.ir.IdentityStrategy;
import io.hexaglue.spi.ir.IdentityWrapperKind;
import io.hexaglue.spi.ir.TypeRef;
import org.junit.jupiter.api.Test;

/**
 * Tests for {@link IdFieldSpec} SPI mapping validation.
 *
 * <p>These tests validate that IdFieldSpec correctly maps SPI Identity
 * to the intermediate representation needed for JPA @Id and @GeneratedValue annotations.
 */
class IdFieldSpecTest {

    @Test
    void from_shouldMapSimpleIdentity_whenUnwrappedUuid() {
        // Given: A simple UUID identity without wrapper
        Identity identity = new Identity(
                "id",
                TypeRef.of("java.util.UUID"),
                TypeRef.of("java.util.UUID"),
                IdentityStrategy.UUID,
                IdentityWrapperKind.NONE);

        // When: Converting to IdFieldSpec
        IdFieldSpec spec = IdFieldSpec.from(identity);

        // Then: Both types should be the same UUID
        assertThat(spec.fieldName()).isEqualTo("id");
        assertThat(spec.javaType().toString()).isEqualTo("java.util.UUID");
        assertThat(spec.unwrappedType().toString()).isEqualTo("java.util.UUID");
        assertThat(spec.strategy()).isEqualTo(IdentityStrategy.UUID);
        assertThat(spec.wrapperKind()).isEqualTo(IdentityWrapperKind.NONE);
        assertThat(spec.isWrapped()).isFalse();
        assertThat(spec.requiresGeneratedValue()).isTrue();
        assertThat(spec.isUuidGenerated()).isTrue();
    }

    @Test
    void from_shouldMapWrappedIdentity_whenRecordWrapper() {
        // Given: A wrapped identity (e.g., record OrderId(UUID value))
        Identity identity = new Identity(
                "orderId",
                TypeRef.of("com.example.OrderId"),
                TypeRef.of("java.util.UUID"),
                IdentityStrategy.ASSIGNED,
                IdentityWrapperKind.RECORD);

        // When: Converting to IdFieldSpec
        IdFieldSpec spec = IdFieldSpec.from(identity);

        // Then: Should distinguish between wrapper and unwrapped type
        assertThat(spec.fieldName()).isEqualTo("orderId");
        assertThat(spec.javaType().toString()).isEqualTo("com.example.OrderId");
        assertThat(spec.unwrappedType().toString()).isEqualTo("java.util.UUID");
        assertThat(spec.isWrapped()).isTrue();
        assertThat(spec.wrapperKind()).isEqualTo(IdentityWrapperKind.RECORD);
    }

    @Test
    void isWrapped_shouldReturnCorrectValue_basedOnWrapperKind() {
        // Given: Identities with different wrapper kinds
        Identity unwrapped = new Identity(
                "id",
                TypeRef.of("java.lang.Long"),
                TypeRef.of("java.lang.Long"),
                IdentityStrategy.IDENTITY,
                IdentityWrapperKind.NONE);

        Identity recordWrapped = new Identity(
                "customerId",
                TypeRef.of("com.example.CustomerId"),
                TypeRef.of("java.lang.Long"),
                IdentityStrategy.IDENTITY,
                IdentityWrapperKind.RECORD);

        Identity classWrapped = new Identity(
                "legacyId",
                TypeRef.of("com.example.LegacyId"),
                TypeRef.of("java.lang.String"),
                IdentityStrategy.NATURAL,
                IdentityWrapperKind.CLASS);

        // When: Converting to specs
        IdFieldSpec unwrappedSpec = IdFieldSpec.from(unwrapped);
        IdFieldSpec recordSpec = IdFieldSpec.from(recordWrapped);
        IdFieldSpec classSpec = IdFieldSpec.from(classWrapped);

        // Then: isWrapped should reflect wrapper presence
        assertThat(unwrappedSpec.isWrapped()).isFalse();
        assertThat(recordSpec.isWrapped()).isTrue();
        assertThat(classSpec.isWrapped()).isTrue();
    }

    @Test
    void requiresGeneratedValue_shouldDelegateToStrategy() {
        // Given: Identities with different generation strategies
        Identity uuidGenerated = new Identity(
                "id",
                TypeRef.of("java.util.UUID"),
                TypeRef.of("java.util.UUID"),
                IdentityStrategy.UUID,
                IdentityWrapperKind.NONE);

        Identity autoGenerated = new Identity(
                "id",
                TypeRef.of("java.lang.Long"),
                TypeRef.of("java.lang.Long"),
                IdentityStrategy.AUTO,
                IdentityWrapperKind.NONE);

        Identity assigned = new Identity(
                "id",
                TypeRef.of("java.lang.Long"),
                TypeRef.of("java.lang.Long"),
                IdentityStrategy.ASSIGNED,
                IdentityWrapperKind.NONE);

        Identity natural = new Identity(
                "isbn",
                TypeRef.of("java.lang.String"),
                TypeRef.of("java.lang.String"),
                IdentityStrategy.NATURAL,
                IdentityWrapperKind.NONE);

        // When: Converting to specs
        IdFieldSpec uuidSpec = IdFieldSpec.from(uuidGenerated);
        IdFieldSpec autoSpec = IdFieldSpec.from(autoGenerated);
        IdFieldSpec assignedSpec = IdFieldSpec.from(assigned);
        IdFieldSpec naturalSpec = IdFieldSpec.from(natural);

        // Then: Generated strategies require @GeneratedValue
        assertThat(uuidSpec.requiresGeneratedValue()).isTrue();
        assertThat(autoSpec.requiresGeneratedValue()).isTrue();
        assertThat(assignedSpec.requiresGeneratedValue()).isFalse();
        assertThat(naturalSpec.requiresGeneratedValue()).isFalse();
    }

    @Test
    void jpaGenerationType_shouldMapCorrectly_forJpaStrategies() {
        // Given: Identities with JPA generation strategies
        Identity auto = new Identity(
                "id",
                TypeRef.of("java.lang.Long"),
                TypeRef.of("java.lang.Long"),
                IdentityStrategy.AUTO,
                IdentityWrapperKind.NONE);

        Identity identity = new Identity(
                "id",
                TypeRef.of("java.lang.Long"),
                TypeRef.of("java.lang.Long"),
                IdentityStrategy.IDENTITY,
                IdentityWrapperKind.NONE);

        Identity sequence = new Identity(
                "id",
                TypeRef.of("java.lang.Long"),
                TypeRef.of("java.lang.Long"),
                IdentityStrategy.SEQUENCE,
                IdentityWrapperKind.NONE);

        Identity table = new Identity(
                "id",
                TypeRef.of("java.lang.Long"),
                TypeRef.of("java.lang.Long"),
                IdentityStrategy.TABLE,
                IdentityWrapperKind.NONE);

        Identity uuid = new Identity(
                "id",
                TypeRef.of("java.util.UUID"),
                TypeRef.of("java.util.UUID"),
                IdentityStrategy.UUID,
                IdentityWrapperKind.NONE);

        // When: Converting to specs and getting JPA type
        IdFieldSpec autoSpec = IdFieldSpec.from(auto);
        IdFieldSpec identitySpec = IdFieldSpec.from(identity);
        IdFieldSpec sequenceSpec = IdFieldSpec.from(sequence);
        IdFieldSpec tableSpec = IdFieldSpec.from(table);
        IdFieldSpec uuidSpec = IdFieldSpec.from(uuid);

        // Then: JPA generation type should match
        assertThat(autoSpec.jpaGenerationType()).isEqualTo("AUTO");
        assertThat(identitySpec.jpaGenerationType()).isEqualTo("IDENTITY");
        assertThat(sequenceSpec.jpaGenerationType()).isEqualTo("SEQUENCE");
        assertThat(tableSpec.jpaGenerationType()).isEqualTo("TABLE");
        assertThat(uuidSpec.jpaGenerationType()).isEqualTo("UUID");
    }

    @Test
    void isDatabaseGenerated_shouldExcludeUuid() {
        // Given: Database-generated and UUID identities
        Identity dbGenerated = new Identity(
                "id",
                TypeRef.of("java.lang.Long"),
                TypeRef.of("java.lang.Long"),
                IdentityStrategy.IDENTITY,
                IdentityWrapperKind.NONE);

        Identity uuidGenerated = new Identity(
                "id",
                TypeRef.of("java.util.UUID"),
                TypeRef.of("java.util.UUID"),
                IdentityStrategy.UUID,
                IdentityWrapperKind.NONE);

        // When: Converting to specs
        IdFieldSpec dbSpec = IdFieldSpec.from(dbGenerated);
        IdFieldSpec uuidSpec = IdFieldSpec.from(uuidGenerated);

        // Then: UUID is not database-generated (application-level)
        assertThat(dbSpec.isDatabaseGenerated()).isTrue();
        assertThat(uuidSpec.isDatabaseGenerated()).isFalse();
    }

    @Test
    void isUuidGenerated_shouldOnlyBeTrueForUuidStrategy() {
        // Given: Different generation strategies
        Identity uuid = new Identity(
                "id",
                TypeRef.of("java.util.UUID"),
                TypeRef.of("java.util.UUID"),
                IdentityStrategy.UUID,
                IdentityWrapperKind.NONE);

        Identity dbIdentity = new Identity(
                "id",
                TypeRef.of("java.lang.Long"),
                TypeRef.of("java.lang.Long"),
                IdentityStrategy.IDENTITY,
                IdentityWrapperKind.NONE);

        // When: Converting to specs
        IdFieldSpec uuidSpec = IdFieldSpec.from(uuid);
        IdFieldSpec dbSpec = IdFieldSpec.from(dbIdentity);

        // Then: Only UUID strategy returns true
        assertThat(uuidSpec.isUuidGenerated()).isTrue();
        assertThat(dbSpec.isUuidGenerated()).isFalse();
    }
}
