name: Feature Request
description: Suggest a new feature or enhancement
title: "[Feature]: "
labels: ["enhancement", "triage"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for suggesting a feature! Please fill out the form below.

  - type: dropdown
    id: modules
    attributes:
      label: Target Module(s)
      description: Which module(s) would this feature affect? You can select multiple.
      multiple: true
      options:
        - hexaglue-syntax-api (Parser abstraction)
        - hexaglue-syntax-spoon (Spoon implementation)
        - hexaglue-arch (Architectural model)
        - hexaglue-spi (Service Provider Interface)
        - hexaglue-core (Analysis engine)
        - hexaglue-maven-plugin (Maven integration)
        - hexaglue-plugin-jpa (JPA generator)
        - hexaglue-plugin-living-doc (Documentation generator)
        - hexaglue-plugin-audit (Architecture audit)
        - hexaglue-testing (Testing harness)
        - hexaglue-benchmarks (Benchmarks)
        - New plugin
        - Other
    validations:
      required: true

  - type: textarea
    id: problem
    attributes:
      label: Problem Statement
      description: What problem does this feature solve? Is it related to a frustration?
      placeholder: I'm always frustrated when...
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: Proposed Solution
      description: Describe the solution you'd like
      placeholder: I would like HexaGlue to...
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives Considered
      description: Describe any alternative solutions or workarounds you've considered
      placeholder: I've tried... but it doesn't work because...

  - type: textarea
    id: example
    attributes:
      label: Example Usage
      description: If applicable, show how this feature would be used
      render: java
      placeholder: |
        // Example domain code
        @AggregateRoot
        public class Order {
            // ...
        }

        // Expected generated code
        @Entity
        public class OrderEntity {
            // ...
        }

  - type: dropdown
    id: breaking
    attributes:
      label: Breaking Change?
      description: Would this feature require breaking changes to existing APIs?
      options:
        - "No"
        - "Yes - SPI change"
        - "Yes - Configuration change"
        - "Yes - Generated code change"
        - "Not sure"
    validations:
      required: true

  - type: checkboxes
    id: contribution
    attributes:
      label: Contribution
      description: Would you be willing to help implement this feature?
      options:
        - label: I would be willing to submit a PR to implement this feature

  - type: checkboxes
    id: checklist
    attributes:
      label: Checklist
      options:
        - label: I have searched existing issues/discussions to ensure this hasn't been requested
          required: true
