/*
 * This Source Code Form is part of the HexaGlue project.
 * Copyright (c) 2026 Scalastic
 *
 * This Source Code Form is subject to the terms of the Mozilla Public
 * License, v. 2.0. If a copy of the MPL was not distributed with this
 * file, You can obtain one at https://mozilla.org/MPL/2.0/.
 *
 * Commercial licensing options are available for organizations wishing
 * to use HexaGlue under terms different from the MPL 2.0.
 * Contact: info@hexaglue.io
 */

package io.hexaglue.core.plugin;

import io.hexaglue.spi.plugin.CodeWriter;
import java.io.IOException;
import java.nio.file.Files;
import java.nio.file.Path;
import java.util.ArrayList;
import java.util.List;

/**
 * {@link CodeWriter} implementation that writes to the file system.
 *
 * <p>Directory structure:
 * <ul>
 *   <li>Java sources: {@code target/generated-sources/hexaglue/}</li>
 *   <li>Resources: {@code target/generated-resources/hexaglue/}</li>
 *   <li>Documentation: {@code target/generated-docs/}</li>
 * </ul>
 */
final class FileSystemCodeWriter implements CodeWriter {

    private final Path outputDirectory;
    private final Path resourcesDirectory;
    private final Path docsDirectory;
    private final List<Path> generatedFiles = new ArrayList<>();

    FileSystemCodeWriter(Path outputDirectory) {
        this.outputDirectory = outputDirectory;
        this.resourcesDirectory =
                outputDirectory.getParent().resolve("generated-resources").resolve("hexaglue");
        this.docsDirectory = outputDirectory.getParent().resolve("generated-docs");
    }

    // =========================================================================
    // Java source generation
    // =========================================================================

    @Override
    public void writeJavaSource(String packageName, String className, String content) throws IOException {
        Path file = resolveJavaSourcePath(packageName, className);
        Files.createDirectories(file.getParent());
        Files.writeString(file, content);
        generatedFiles.add(file);
    }

    @Override
    public boolean exists(String packageName, String className) {
        return Files.exists(resolveJavaSourcePath(packageName, className));
    }

    @Override
    public void delete(String packageName, String className) throws IOException {
        Path file = resolveJavaSourcePath(packageName, className);
        if (Files.exists(file)) {
            Files.delete(file);
            generatedFiles.remove(file);
        }
    }

    @Override
    public Path getOutputDirectory() {
        return outputDirectory;
    }

    private Path resolveJavaSourcePath(String packageName, String className) {
        String relativePath = packageName.replace('.', '/') + "/" + className + ".java";
        return outputDirectory.resolve(relativePath);
    }

    // =========================================================================
    // Resource generation
    // =========================================================================

    @Override
    public void writeResource(String path, String content) throws IOException {
        Path file = resourcesDirectory.resolve(path);
        Files.createDirectories(file.getParent());
        Files.writeString(file, content);
        generatedFiles.add(file);
    }

    @Override
    public boolean resourceExists(String path) {
        return Files.exists(resourcesDirectory.resolve(path));
    }

    @Override
    public void deleteResource(String path) throws IOException {
        Path file = resourcesDirectory.resolve(path);
        if (Files.exists(file)) {
            Files.delete(file);
            generatedFiles.remove(file);
        }
    }

    // =========================================================================
    // Documentation generation
    // =========================================================================

    @Override
    public void writeDoc(String path, String content) throws IOException {
        Path file = docsDirectory.resolve(path);
        Files.createDirectories(file.getParent());
        Files.writeString(file, content);
        generatedFiles.add(file);
    }

    @Override
    public boolean docExists(String path) {
        return Files.exists(docsDirectory.resolve(path));
    }

    @Override
    public void deleteDoc(String path) throws IOException {
        Path file = docsDirectory.resolve(path);
        if (Files.exists(file)) {
            Files.delete(file);
            generatedFiles.remove(file);
        }
    }

    @Override
    public Path getDocsOutputDirectory() {
        return docsDirectory;
    }

    // =========================================================================
    // Internal API
    // =========================================================================

    /**
     * Returns all files generated by this writer.
     */
    List<Path> getGeneratedFiles() {
        return List.copyOf(generatedFiles);
    }
}
