/*
 * This Source Code Form is part of the HexaGlue project.
 * Copyright (c) 2026 Scalastic
 *
 * This Source Code Form is subject to the terms of the Mozilla Public
 * License, v. 2.0. If a copy of the MPL was not distributed with this
 * file, You can obtain one at https://mozilla.org/MPL/2.0/.
 *
 * Commercial licensing options are available for organizations wishing
 * to use HexaGlue under terms different from the MPL 2.0.
 * Contact: info@hexaglue.io
 */

package io.hexaglue.core.plugin;

import java.nio.file.Path;
import java.util.List;
import java.util.Map;
import java.util.Optional;

/**
 * Result of executing all plugins.
 *
 * @param pluginResults results for each executed plugin
 */
public record PluginExecutionResult(List<PluginResult> pluginResults) {

    /**
     * Creates an empty result (no plugins executed).
     */
    public static PluginExecutionResult empty() {
        return new PluginExecutionResult(List.of());
    }

    /**
     * Returns true if all plugins executed successfully.
     */
    public boolean isSuccess() {
        return pluginResults.stream().allMatch(PluginResult::success);
    }

    /**
     * Returns the total number of files generated by all plugins.
     */
    public int totalGeneratedFiles() {
        return pluginResults.stream().mapToInt(r -> r.generatedFiles().size()).sum();
    }

    /**
     * Returns all generated files from all plugins.
     */
    public List<Path> allGeneratedFiles() {
        return pluginResults.stream().flatMap(r -> r.generatedFiles().stream()).toList();
    }

    /**
     * Returns all errors from all plugins.
     */
    public List<PluginDiagnostic> allErrors() {
        return pluginResults.stream().flatMap(r -> r.errors().stream()).toList();
    }

    /**
     * Returns the number of plugins executed.
     */
    public int pluginCount() {
        return pluginResults.size();
    }

    /**
     * Gets the outputs from a specific plugin.
     *
     * @param pluginId the plugin identifier
     * @return the plugin outputs, or empty map if not found
     */
    public Map<String, Object> getPluginOutputs(String pluginId) {
        return pluginResults.stream()
                .filter(r -> r.pluginId().equals(pluginId))
                .findFirst()
                .map(PluginResult::outputs)
                .orElse(Map.of());
    }

    /**
     * Gets a typed output from any plugin that provides it.
     *
     * <p>Searches all plugin results for an output with the given key and type.
     * This is useful for retrieving shared data like AuditSnapshot without
     * knowing which specific plugin produced it.
     *
     * @param key the output key
     * @param type the expected type
     * @param <T> the value type
     * @return the output value, or empty if not found or wrong type
     */
    // Suppressed: safe cast to T after type.isInstance() check guarantees the value is of type T
    @SuppressWarnings("unchecked")
    public <T> Optional<T> findOutput(String key, Class<T> type) {
        for (PluginResult result : pluginResults) {
            Object value = result.outputs().get(key);
            if (value != null && type.isInstance(value)) {
                return Optional.of((T) value);
            }
        }
        return Optional.empty();
    }
}
