package io.hexaglue.core.plugin;

import java.nio.file.Path;
import java.util.List;

/**
 * Result of executing all plugins.
 *
 * @param pluginResults results for each executed plugin
 */
public record PluginExecutionResult(List<PluginResult> pluginResults) {

    /**
     * Creates an empty result (no plugins executed).
     */
    public static PluginExecutionResult empty() {
        return new PluginExecutionResult(List.of());
    }

    /**
     * Returns true if all plugins executed successfully.
     */
    public boolean isSuccess() {
        return pluginResults.stream().allMatch(PluginResult::success);
    }

    /**
     * Returns the total number of files generated by all plugins.
     */
    public int totalGeneratedFiles() {
        return pluginResults.stream().mapToInt(r -> r.generatedFiles().size()).sum();
    }

    /**
     * Returns all generated files from all plugins.
     */
    public List<Path> allGeneratedFiles() {
        return pluginResults.stream().flatMap(r -> r.generatedFiles().stream()).toList();
    }

    /**
     * Returns all errors from all plugins.
     */
    public List<PluginDiagnostic> allErrors() {
        return pluginResults.stream().flatMap(r -> r.errors().stream()).toList();
    }

    /**
     * Returns the number of plugins executed.
     */
    public int pluginCount() {
        return pluginResults.size();
    }
}
