package io.hexaglue.core.plugin;

import java.nio.file.Path;
import java.util.List;

/**
 * Result of executing a single plugin.
 *
 * @param pluginId the plugin identifier
 * @param success true if execution completed without errors
 * @param generatedFiles files generated by this plugin
 * @param diagnostics diagnostics reported by the plugin
 * @param executionTimeMs execution time in milliseconds
 * @param error the exception if execution failed, null otherwise
 */
public record PluginResult(
        String pluginId,
        boolean success,
        List<Path> generatedFiles,
        List<PluginDiagnostic> diagnostics,
        long executionTimeMs,
        Throwable error) {

    /**
     * Returns all error diagnostics.
     */
    public List<PluginDiagnostic> errors() {
        return diagnostics.stream().filter(PluginDiagnostic::isError).toList();
    }
}
