/*
 * This Source Code Form is part of the HexaGlue project.
 * Copyright (c) 2026 Scalastic
 *
 * This Source Code Form is subject to the terms of the Mozilla Public
 * License, v. 2.0. If a copy of the MPL was not distributed with this
 * file, You can obtain one at https://mozilla.org/MPL/2.0/.
 *
 * Commercial licensing options are available for organizations wishing
 * to use HexaGlue under terms different from the MPL 2.0.
 * Contact: info@hexaglue.io
 */

package io.hexaglue.core.plugin;

import java.nio.file.Path;
import java.util.List;
import java.util.Map;
import java.util.Set;

/**
 * Result of executing a single plugin.
 *
 * @param pluginId the plugin identifier
 * @param success true if execution completed without errors
 * @param generatedFiles files generated by this plugin
 * @param diagnostics diagnostics reported by the plugin
 * @param executionTimeMs execution time in milliseconds
 * @param error the exception if execution failed, null otherwise
 * @param outputs plugin outputs stored via setOutput() during execution
 * @param usedSourceRoots source root directories actually written to by this plugin
 * @since 5.0.0 added usedSourceRoots
 */
public record PluginResult(
        String pluginId,
        boolean success,
        List<Path> generatedFiles,
        List<PluginDiagnostic> diagnostics,
        long executionTimeMs,
        Throwable error,
        Map<String, Object> outputs,
        Set<Path> usedSourceRoots) {

    /**
     * Compact constructor that ensures outputs and usedSourceRoots are never null.
     */
    public PluginResult {
        outputs = outputs != null ? Map.copyOf(outputs) : Map.of();
        usedSourceRoots = usedSourceRoots != null ? Set.copyOf(usedSourceRoots) : Set.of();
    }

    /**
     * Backwards-compatible constructor without usedSourceRoots.
     */
    public PluginResult(
            String pluginId,
            boolean success,
            List<Path> generatedFiles,
            List<PluginDiagnostic> diagnostics,
            long executionTimeMs,
            Throwable error,
            Map<String, Object> outputs) {
        this(pluginId, success, generatedFiles, diagnostics, executionTimeMs, error, outputs, Set.of());
    }

    /**
     * Returns all error diagnostics.
     */
    public List<PluginDiagnostic> errors() {
        return diagnostics.stream().filter(PluginDiagnostic::isError).toList();
    }

    /**
     * Creates a skipped plugin result.
     *
     * @param pluginId the plugin identifier
     * @param reason the reason the plugin was skipped
     * @return a failed result with the skip reason
     */
    public static PluginResult skipped(String pluginId, String reason) {
        PluginDiagnostic diagnostic = new PluginDiagnostic(PluginDiagnostic.Severity.WARNING, reason, null);
        return new PluginResult(pluginId, false, List.of(), List.of(diagnostic), 0, null, Map.of());
    }
}
