/*
 * This Source Code Form is part of the HexaGlue project.
 * Copyright (c) 2026 Scalastic
 *
 * This Source Code Form is subject to the terms of the Mozilla Public
 * License, v. 2.0. If a copy of the MPL was not distributed with this
 * file, You can obtain one at https://mozilla.org/MPL/2.0/.
 *
 * Commercial licensing options are available for organizations wishing
 * to use HexaGlue under terms different from the MPL 2.0.
 * Contact: info@hexaglue.io
 */

package io.hexaglue.arch.model;

import io.hexaglue.arch.ElementKind;

/**
 * Kinds of architectural types in the new type hierarchy.
 *
 * <p>This enum represents the classification of types in a DDD/Hexagonal Architecture
 * application. It mirrors {@link ElementKind} but is specifically designed for the
 * new {@link ArchType} hierarchy.</p>
 *
 * <h2>Categories</h2>
 * <ul>
 *   <li><strong>Domain</strong>: AGGREGATE_ROOT, ENTITY, VALUE_OBJECT, IDENTIFIER,
 *       DOMAIN_EVENT, DOMAIN_SERVICE</li>
 *   <li><strong>Ports</strong>: DRIVING_PORT, DRIVEN_PORT</li>
 *   <li><strong>Application</strong>: APPLICATION_SERVICE, COMMAND_HANDLER, QUERY_HANDLER</li>
 *   <li><strong>Fallback</strong>: UNCLASSIFIED</li>
 * </ul>
 *
 * <h2>Note on Adapters</h2>
 * <p>Adapters (DRIVING_ADAPTER, DRIVEN_ADAPTER) are NOT included because they are
 * generated by plugins, not classified from source code.</p>
 *
 * @since 4.1.0
 */
public enum ArchKind {

    // ===== Domain =====

    /**
     * An aggregate root - the entry point to an aggregate that ensures consistency.
     */
    AGGREGATE_ROOT,

    /**
     * A domain entity - has identity and lifecycle.
     */
    ENTITY,

    /**
     * A value object - immutable, identified by its attributes.
     */
    VALUE_OBJECT,

    /**
     * An identifier - a value object that represents an entity's identity.
     */
    IDENTIFIER,

    /**
     * A domain event - represents something that happened in the domain.
     */
    DOMAIN_EVENT,

    /**
     * A domain service - stateless operation that doesn't naturally fit in an entity or value object.
     */
    DOMAIN_SERVICE,

    // ===== Ports =====

    /**
     * A driving port (primary/inbound) - interface exposed to the outside world.
     */
    DRIVING_PORT,

    /**
     * A driven port (secondary/outbound) - interface for external dependencies.
     */
    DRIVEN_PORT,

    // ===== Application =====

    /**
     * An application service - orchestrates use cases using domain and ports.
     */
    APPLICATION_SERVICE,

    /**
     * A command handler - handles commands and modifies state.
     */
    COMMAND_HANDLER,

    /**
     * A query handler - handles queries and returns data without modifying state.
     */
    QUERY_HANDLER,

    // ===== Fallback =====

    /**
     * An unclassified type - could not be classified with sufficient confidence.
     */
    UNCLASSIFIED;

    /**
     * Returns {@code true} if this is a domain type.
     *
     * <p>Domain types include: AGGREGATE_ROOT, ENTITY, VALUE_OBJECT, IDENTIFIER,
     * DOMAIN_EVENT, DOMAIN_SERVICE.</p>
     *
     * @return true if this is a domain kind
     */
    public boolean isDomain() {
        return switch (this) {
            case AGGREGATE_ROOT, ENTITY, VALUE_OBJECT, IDENTIFIER, DOMAIN_EVENT, DOMAIN_SERVICE -> true;
            default -> false;
        };
    }

    /**
     * Returns {@code true} if this is a port type (DRIVING_PORT or DRIVEN_PORT).
     *
     * @return true if this is a port kind
     */
    public boolean isPort() {
        return this == DRIVING_PORT || this == DRIVEN_PORT;
    }

    /**
     * Returns {@code true} if this is an application type.
     *
     * <p>Application types include: APPLICATION_SERVICE, COMMAND_HANDLER, QUERY_HANDLER.</p>
     *
     * @return true if this is an application kind
     */
    public boolean isApplication() {
        return switch (this) {
            case APPLICATION_SERVICE, COMMAND_HANDLER, QUERY_HANDLER -> true;
            default -> false;
        };
    }

    /**
     * Converts an {@link ElementKind} to an {@link ArchKind}.
     *
     * <p>Adapter kinds (DRIVING_ADAPTER, DRIVEN_ADAPTER) and other unmapped kinds
     * are converted to UNCLASSIFIED since adapters are generated, not classified.</p>
     *
     * @param kind the element kind to convert
     * @return the corresponding ArchKind, or UNCLASSIFIED for unmapped kinds
     */
    public static ArchKind fromElementKind(ElementKind kind) {
        return switch (kind) {
            case AGGREGATE_ROOT -> AGGREGATE_ROOT;
            case ENTITY -> ENTITY;
            case VALUE_OBJECT -> VALUE_OBJECT;
            case IDENTIFIER -> IDENTIFIER;
            case DOMAIN_EVENT, EXTERNALIZED_EVENT -> DOMAIN_EVENT;
            case DOMAIN_SERVICE -> DOMAIN_SERVICE;
            case DRIVING_PORT -> DRIVING_PORT;
            case DRIVEN_PORT -> DRIVEN_PORT;
            case APPLICATION_SERVICE -> APPLICATION_SERVICE;
            case INBOUND_ONLY -> COMMAND_HANDLER;
            case OUTBOUND_ONLY, SAGA -> QUERY_HANDLER;
            case UNCLASSIFIED -> UNCLASSIFIED;
            // Adapters and AGGREGATE are not classified - they're generated or deprecated
            case DRIVING_ADAPTER, DRIVEN_ADAPTER, AGGREGATE -> UNCLASSIFIED;
        };
    }
}
