/*
 * This Source Code Form is part of the HexaGlue project.
 * Copyright (c) 2026 Scalastic
 *
 * This Source Code Form is subject to the terms of the Mozilla Public
 * License, v. 2.0. If a copy of the MPL was not distributed with this
 * file, You can obtain one at https://mozilla.org/MPL/2.0/.
 *
 * Commercial licensing options are available for organizations wishing
 * to use HexaGlue under terms different from the MPL 2.0.
 * Contact: info@hexaglue.io
 */

package io.hexaglue.plugin.jpa;

import static io.hexaglue.plugin.jpa.TestFixtures.*;
import static org.assertj.core.api.Assertions.assertThat;

import io.hexaglue.spi.ir.*;
import java.util.List;
import java.util.Optional;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.DisplayName;
import org.junit.jupiter.api.Nested;
import org.junit.jupiter.api.Test;

@DisplayName("JpaRepositoryGenerator")
class JpaRepositoryGeneratorTest {

    private static final String INFRA_PKG = "com.example.infrastructure.persistence";
    private static final String DOMAIN_PKG = "com.example.domain";

    private JpaRepositoryGenerator generator;
    private JpaConfig config;

    @BeforeEach
    void setUp() {
        config = JpaConfig.defaults();
        generator = new JpaRepositoryGenerator(INFRA_PKG, config);
    }

    @Nested
    @DisplayName("generateRepository()")
    class GenerateRepositoryTests {

        @Test
        @DisplayName("should generate package declaration")
        void shouldGeneratePackageDeclaration() {
            DomainType type = simpleAggregateRoot("Order", DOMAIN_PKG);

            String code = generator.generateRepository(type);

            assertThat(code).startsWith("package " + INFRA_PKG + ";");
        }

        @Test
        @DisplayName("should generate @Repository annotation")
        void shouldGenerateRepositoryAnnotation() {
            DomainType type = simpleAggregateRoot("Order", DOMAIN_PKG);

            String code = generator.generateRepository(type);

            assertThat(code).contains("@Repository");
        }

        @Test
        @DisplayName("should extend JpaRepository with correct generics")
        void shouldExtendJpaRepositoryWithCorrectGenerics() {
            DomainType type = simpleAggregateRoot("Order", DOMAIN_PKG);

            String code = generator.generateRepository(type);

            assertThat(code).contains("extends JpaRepository<OrderEntity, UUID>");
        }

        @Test
        @DisplayName("should use Long as ID type for raw Long identity")
        void shouldUseLongAsIdTypeForRawLongIdentity() {
            DomainType type = simpleEntity("Order", DOMAIN_PKG);

            String code = generator.generateRepository(type);

            assertThat(code).contains("extends JpaRepository<OrderEntity, Long>");
        }

        @Test
        @DisplayName("should generate interface with repository suffix")
        void shouldGenerateInterfaceWithRepositorySuffix() {
            DomainType type = simpleAggregateRoot("Order", DOMAIN_PKG);

            String code = generator.generateRepository(type);

            assertThat(code).contains("public interface OrderJpaRepository");
        }

        @Test
        @DisplayName("should import required classes")
        void shouldImportRequiredClasses() {
            DomainType type = simpleAggregateRoot("Order", DOMAIN_PKG);

            String code = generator.generateRepository(type);

            assertThat(code).contains("import org.springframework.data.jpa.repository.JpaRepository;");
            assertThat(code).contains("import org.springframework.stereotype.Repository;");
            assertThat(code).contains("import java.util.UUID;");
        }

        @Test
        @DisplayName("should generate javadoc")
        void shouldGenerateJavadoc() {
            DomainType type = simpleAggregateRoot("Order", DOMAIN_PKG);

            String code = generator.generateRepository(type);

            assertThat(code).contains("Spring Data JPA repository for {@link OrderEntity}");
            assertThat(code).contains("Provides standard CRUD operations");
            assertThat(code).contains("Generated by HexaGlue JPA Plugin");
        }
    }

    @Nested
    @DisplayName("Query method generation")
    class QueryMethodGenerationTests {

        @Test
        @DisplayName("should generate findBy methods for String properties")
        void shouldGenerateFindByMethodsForStringProperties() {
            DomainType type = simpleAggregateRoot("Customer", DOMAIN_PKG);

            String code = generator.generateRepository(type);

            assertThat(code).contains("java.util.List<CustomerEntity> findByName(String name);");
        }

        @Test
        @DisplayName("should generate findBy methods with javadoc")
        void shouldGenerateFindByMethodsWithJavadoc() {
            DomainType type = simpleAggregateRoot("Customer", DOMAIN_PKG);

            String code = generator.generateRepository(type);

            assertThat(code).contains("Finds entities by name");
            assertThat(code).contains("@param name the name to search for");
            assertThat(code).contains("@return list of matching entities");
        }

        @Test
        @DisplayName("should NOT generate findBy for non-queryable types")
        void shouldNotGenerateFindByForNonQueryableTypes() {
            // Money has BigDecimal which is not in the queryable types list
            DomainType vo = moneyValueObject(DOMAIN_PKG);

            String code = generator.generateRepository(vo);

            assertThat(code).doesNotContain("findByAmount");
        }

        @Test
        @DisplayName("should limit findBy methods to 3")
        void shouldLimitFindByMethodsToThree() {
            List<DomainProperty> manyProps = List.of(
                    identityProperty("id", uuidType()),
                    simpleProperty("name", stringType()),
                    simpleProperty("email", stringType()),
                    simpleProperty("phone", stringType()),
                    simpleProperty("address", stringType()),
                    simpleProperty("city", stringType()));

            DomainType type = new DomainType(
                    DOMAIN_PKG + ".Customer",
                    "Customer",
                    DOMAIN_PKG,
                    DomainKind.AGGREGATE_ROOT,
                    ConfidenceLevel.HIGH,
                    JavaConstruct.CLASS,
                    Optional.of(rawUuidIdentity("id")),
                    manyProps,
                    List.of(),
                    List.of(),
                    SourceRef.unknown());

            String code = generator.generateRepository(type);

            // Count occurrences of findBy
            long findByCount =
                    code.lines().filter(line -> line.contains("findBy")).count();
            assertThat(findByCount).isLessThanOrEqualTo(3);
        }
    }

    @Nested
    @DisplayName("Custom suffix configuration")
    class CustomSuffixTests {

        @Test
        @DisplayName("should use custom repository suffix")
        void shouldUseCustomRepositorySuffix() {
            JpaConfig customConfig =
                    new JpaConfig("Entity", "Repository", "Adapter", "Mapper", "", false, false, true, true, true);
            JpaRepositoryGenerator gen = new JpaRepositoryGenerator(INFRA_PKG, customConfig);
            DomainType type = simpleAggregateRoot("Order", DOMAIN_PKG);

            String code = gen.generateRepository(type);

            assertThat(code).contains("public interface OrderRepository");
        }

        @Test
        @DisplayName("should use custom entity suffix in generics")
        void shouldUseCustomEntitySuffixInGenerics() {
            JpaConfig customConfig =
                    new JpaConfig("Jpa", "JpaRepository", "Adapter", "Mapper", "", false, false, true, true, true);
            JpaRepositoryGenerator gen = new JpaRepositoryGenerator(INFRA_PKG, customConfig);
            DomainType type = simpleAggregateRoot("Order", DOMAIN_PKG);

            String code = gen.generateRepository(type);

            assertThat(code).contains("extends JpaRepository<OrderJpa, UUID>");
        }
    }

    @Nested
    @DisplayName("ID type handling")
    class IdTypeHandlingTests {

        @Test
        @DisplayName("should handle UUID identity")
        void shouldHandleUuidIdentity() {
            DomainType type = simpleAggregateRoot("Order", DOMAIN_PKG);

            String code = generator.generateRepository(type);

            assertThat(code).contains("JpaRepository<OrderEntity, UUID>");
        }

        @Test
        @DisplayName("should handle Long identity")
        void shouldHandleLongIdentity() {
            DomainType type = simpleEntity("Order", DOMAIN_PKG);

            String code = generator.generateRepository(type);

            assertThat(code).contains("JpaRepository<OrderEntity, Long>");
        }

        @Test
        @DisplayName("should default to Long when no identity")
        void shouldDefaultToLongWhenNoIdentity() {
            DomainType type = new DomainType(
                    DOMAIN_PKG + ".Order",
                    "Order",
                    DOMAIN_PKG,
                    DomainKind.AGGREGATE_ROOT,
                    ConfidenceLevel.HIGH,
                    JavaConstruct.CLASS,
                    Optional.empty(),
                    List.of(simpleProperty("name", stringType())),
                    List.of(),
                    List.of(),
                    SourceRef.unknown());

            String code = generator.generateRepository(type);

            assertThat(code).contains("JpaRepository<OrderEntity, Long>");
        }
    }
}
