/*
 * This Source Code Form is part of the HexaGlue project.
 * Copyright (c) 2026 Scalastic
 *
 * This Source Code Form is subject to the terms of the Mozilla Public
 * License, v. 2.0. If a copy of the MPL was not distributed with this
 * file, You can obtain one at https://mozilla.org/MPL/2.0/.
 *
 * Commercial licensing options are available for organizations wishing
 * to use HexaGlue under terms different from the MPL 2.0.
 * Contact: info@hexaglue.io
 */

package io.hexaglue.plugin.audit.adapter.report;

import io.hexaglue.plugin.audit.domain.model.report.*;
import java.util.Locale;

/**
 * Renders audit reports to console-friendly plain text.
 *
 * <p>This renderer produces compact output suitable for terminal display,
 * with optional ANSI color codes for severity highlighting.
 *
 * @since 5.0.0
 */
public class ConsoleRenderer implements ReportRenderer {

    private static final String ANSI_RESET = "\u001B[0m";
    private static final String ANSI_RED = "\u001B[31m";
    private static final String ANSI_GREEN = "\u001B[32m";
    private static final String ANSI_YELLOW = "\u001B[33m";
    private static final String ANSI_CYAN = "\u001B[36m";
    private static final String ANSI_PURPLE = "\u001B[35m";
    private static final String ANSI_BOLD = "\u001B[1m";

    private final boolean useColors;

    /**
     * Creates a console renderer with colors enabled.
     */
    public ConsoleRenderer() {
        this(true);
    }

    /**
     * Creates a console renderer with configurable colors.
     *
     * @param useColors whether to use ANSI color codes
     */
    public ConsoleRenderer(boolean useColors) {
        this.useColors = useColors;
    }

    @Override
    public ReportFormat format() {
        return ReportFormat.CONSOLE;
    }

    @Override
    public String render(ReportData data) {
        return render(data, null);
    }

    @Override
    public String render(ReportData data, DiagramSet diagrams) {
        StringBuilder out = new StringBuilder();

        // Header
        out.append("\n");
        out.append(bold("=".repeat(70))).append("\n");
        out.append(bold("  HEXAGLUE ARCHITECTURE AUDIT REPORT")).append("\n");
        out.append(bold("=".repeat(70))).append("\n\n");

        out.append("  Project: ").append(data.metadata().projectName()).append("\n");
        out.append("  Version: ").append(data.metadata().projectVersion()).append("\n");
        out.append("  Duration: ").append(data.metadata().duration()).append("\n\n");

        // Verdict
        renderVerdict(out, data.verdict());

        // Issues summary
        renderIssuesSummary(out, data.issues());

        // Remediation summary
        renderRemediationSummary(out, data.remediation());

        out.append(bold("-".repeat(70))).append("\n");
        out.append("  Generated by HexaGlue ").append(data.metadata().hexaglueVersion()).append("\n");
        out.append(bold("-".repeat(70))).append("\n\n");

        return out.toString();
    }

    private void renderVerdict(StringBuilder out, Verdict verdict) {
        out.append(bold("-".repeat(70))).append("\n");
        out.append(bold("  VERDICT")).append("\n");
        out.append(bold("-".repeat(70))).append("\n\n");

        // Score with color
        String scoreColor = verdict.score() >= 80 ? ANSI_GREEN :
                verdict.score() >= 60 ? ANSI_YELLOW : ANSI_RED;

        out.append("  Score:  ").append(color(verdict.score() + "/100", scoreColor));
        out.append("  |  Grade: ").append(bold(verdict.grade()));
        out.append("  |  Status: ").append(colorStatus(verdict.status())).append("\n\n");

        out.append("  ").append(verdict.summary()).append("\n\n");

        // KPIs
        if (!verdict.kpis().isEmpty()) {
            out.append("  KPIs:\n");
            for (KPI kpi : verdict.kpis()) {
                String icon = switch (kpi.status()) {
                    case OK -> color("\u2713", ANSI_GREEN);
                    case WARNING -> color("!", ANSI_YELLOW);
                    case CRITICAL -> color("\u2717", ANSI_RED);
                };
                out.append("    ").append(icon).append(" ")
                        .append(padRight(kpi.name(), 25))
                        .append(String.format(Locale.ROOT, "%6.0f%%", kpi.value()))
                        .append(" (threshold: ").append(String.format(Locale.ROOT, "%.0f", kpi.threshold())).append("%)\n");
            }
            out.append("\n");
        }

        // Immediate action
        if (verdict.immediateAction().required()) {
            out.append(color("  \u26A0 IMMEDIATE ACTION REQUIRED: ", ANSI_RED));
            out.append(verdict.immediateAction().message()).append("\n\n");
        }
    }

    private void renderIssuesSummary(StringBuilder out, IssuesSummary issues) {
        ViolationCounts counts = issues.summary();

        out.append(bold("-".repeat(70))).append("\n");
        out.append(bold("  ISSUES")).append("\n");
        out.append(bold("-".repeat(70))).append("\n\n");

        if (counts.total() == 0) {
            out.append(color("  \u2713 No issues detected!\n\n", ANSI_GREEN));
            return;
        }

        out.append("  Total: ").append(counts.total()).append(" issue(s)\n\n");

        // Severity breakdown
        if (counts.blockers() > 0) {
            out.append("    ").append(color("\u2588", ANSI_PURPLE)).append(" BLOCKER:  ").append(counts.blockers()).append("\n");
        }
        if (counts.criticals() > 0) {
            out.append("    ").append(color("\u2588", ANSI_RED)).append(" CRITICAL: ").append(counts.criticals()).append("\n");
        }
        if (counts.majors() > 0) {
            out.append("    ").append(color("\u2588", ANSI_YELLOW)).append(" MAJOR:    ").append(counts.majors()).append("\n");
        }
        if (counts.minors() > 0) {
            out.append("    ").append(color("\u2588", ANSI_CYAN)).append(" MINOR:    ").append(counts.minors()).append("\n");
        }
        if (counts.infos() > 0) {
            out.append("    ").append(color("\u2588", ANSI_GREEN)).append(" INFO:     ").append(counts.infos()).append("\n");
        }
        out.append("\n");

        // Top issues
        int shown = 0;
        for (IssueGroup group : issues.groups()) {
            for (IssueEntry issue : group.violations()) {
                if (shown >= 5) break;
                String sevColor = switch (issue.severity()) {
                    case BLOCKER -> ANSI_PURPLE;
                    case CRITICAL -> ANSI_RED;
                    case MAJOR -> ANSI_YELLOW;
                    case MINOR -> ANSI_CYAN;
                    case INFO -> ANSI_GREEN;
                };
                out.append("    ").append(color(padRight("[" + issue.severity() + "]", 12), sevColor));
                out.append(truncate(issue.title(), 50)).append("\n");
                shown++;
            }
            if (shown >= 5) break;
        }
        if (counts.total() > 5) {
            out.append("    ... and ").append(counts.total() - 5).append(" more issues\n");
        }
        out.append("\n");
    }

    private void renderRemediationSummary(StringBuilder out, RemediationPlan plan) {
        out.append(bold("-".repeat(70))).append("\n");
        out.append(bold("  REMEDIATION")).append("\n");
        out.append(bold("-".repeat(70))).append("\n\n");

        if (plan.actions().isEmpty()) {
            out.append(color("  \u2713 No remediation required!\n\n", ANSI_GREEN));
            return;
        }

        TotalEffort effort = plan.totalEffort();
        out.append("  Total Effort: ").append(String.format(Locale.ROOT, "%.1f", effort.days())).append(" days");
        effort.costOpt().ifPresent(cost ->
                out.append(" (~").append(cost.currency()).append(" ")
                        .append(String.format(Locale.ROOT, "%.0f", cost.amount())).append(")"));
        out.append("\n\n");

        // Top actions
        int shown = 0;
        for (RemediationAction action : plan.actions()) {
            if (shown >= 3) break;
            out.append("    ").append(action.priority()).append(". ");
            out.append(truncate(action.title(), 45));
            out.append(" (").append(String.format(Locale.ROOT, "%.1f", action.effort().days())).append("d)\n");
            shown++;
        }
        if (plan.actions().size() > 3) {
            out.append("    ... and ").append(plan.actions().size() - 3).append(" more actions\n");
        }
        out.append("\n");
    }

    private String colorStatus(ReportStatus status) {
        return switch (status) {
            case PASSED -> color("PASSED", ANSI_GREEN);
            case PASSED_WITH_WARNINGS -> color("PASSED (with warnings)", ANSI_YELLOW);
            case FAILED -> color("FAILED", ANSI_RED);
        };
    }

    private String color(String text, String ansiCode) {
        if (!useColors) return text;
        return ansiCode + text + ANSI_RESET;
    }

    private String bold(String text) {
        if (!useColors) return text;
        return ANSI_BOLD + text + ANSI_RESET;
    }

    private String padRight(String text, int width) {
        if (text.length() >= width) return text;
        return text + " ".repeat(width - text.length());
    }

    private String truncate(String text, int maxLength) {
        if (text == null || text.length() <= maxLength) return text;
        return text.substring(0, maxLength - 3) + "...";
    }
}
