/*
 * This Source Code Form is part of the HexaGlue project.
 * Copyright (c) 2026 Scalastic
 *
 * This Source Code Form is subject to the terms of the Mozilla Public
 * License, v. 2.0. If a copy of the MPL was not distributed with this
 * file, You can obtain one at https://mozilla.org/MPL/2.0/.
 *
 * Commercial licensing options are available for organizations wishing
 * to use HexaGlue under terms different from the MPL 2.0.
 * Contact: info@hexaglue.io
 */

package io.hexaglue.plugin.audit.adapter.report;

import io.hexaglue.plugin.audit.adapter.report.model.ArchitectureAnalysis;
import io.hexaglue.plugin.audit.adapter.report.model.AuditReport;
import io.hexaglue.plugin.audit.adapter.report.model.ComponentInventory;
import io.hexaglue.plugin.audit.adapter.report.model.ExecutiveSummary;
import io.hexaglue.plugin.audit.adapter.report.model.HealthScore;
import io.hexaglue.plugin.audit.adapter.report.model.MetricEntry;
import io.hexaglue.plugin.audit.adapter.report.model.PortMatrixEntry;
import io.hexaglue.plugin.audit.adapter.report.model.TechnicalDebtSummary;
import io.hexaglue.plugin.audit.adapter.report.model.ViolationEntry;
import io.hexaglue.plugin.audit.domain.model.Recommendation;
import java.time.ZoneId;
import java.time.format.DateTimeFormatter;
import java.util.Objects;

/**
 * Generates audit reports in GitHub-flavored Markdown format.
 *
 * <p>This generator produces Markdown that renders well on GitHub and other
 * Markdown viewers. Features include:
 * <ul>
 *   <li>Emoji indicators for status (pass/fail)</li>
 *   <li>Tables for violations and metrics</li>
 *   <li>Collapsible sections using HTML details tags</li>
 *   <li>Code formatting for technical details</li>
 * </ul>
 *
 * @since 1.0.0
 */
public final class MarkdownReportGenerator implements ReportGenerator {

    private static final DateTimeFormatter TIMESTAMP_FORMATTER = DateTimeFormatter.ofPattern("yyyy-MM-dd HH:mm:ss");

    @Override
    public ReportFormat format() {
        return ReportFormat.MARKDOWN;
    }

    @Override
    public String generate(AuditReport report) {
        Objects.requireNonNull(report, "report required");

        StringBuilder md = new StringBuilder();

        // Title
        md.append("# HexaGlue Architecture Audit Report\n\n");

        // Metadata
        md.append("**Application**: ").append(report.metadata().projectName()).append("  \n");
        md.append("**Analyzed Version**: ").append(report.metadata().projectVersion()).append("  \n");
        md.append("**Audit Date**: ")
                .append(TIMESTAMP_FORMATTER.format(report.metadata().timestamp().atZone(ZoneId.systemDefault())))
                .append("  \n");
        md.append("**Duration**: ").append(report.metadata().duration()).append("  \n");
        md.append("**Generated by**: HexaGlue AuditPlugin v")
                .append(report.metadata().hexaglueVersion())
                .append("  \n\n");

        // Separator
        md.append("---\n\n");

        // Compliance Summary in blockquote
        String statusIcon = report.summary().passed() ? "✅ PASSED" : "❌ FAILED";
        md.append("> ## 🛡️ Compliance Summary\n>\n");
        md.append("> | Global Status | Health Score | DDD Compliance | Hexagonal Compliance |\n");
        md.append("> |:-------------:|:------------:|:--------------:|:--------------------:|\n");
        md.append("> | **").append(statusIcon).append("** | **")
                .append(report.healthScore().overall())
                .append("/100 (")
                .append(report.healthScore().grade())
                .append(")** | **")
                .append(report.dddCompliancePercent())
                .append("%** | **")
                .append(report.hexCompliancePercent())
                .append("%** |\n\n");

        // Table of Contents
        appendTableOfContents(md);

        // Executive Summary
        appendExecutiveSummary(md, report.executiveSummary());

        // Health Score
        appendHealthScore(md, report.healthScore());

        // Component Inventory
        appendComponentInventory(md, report.inventory());

        // DDD Compliance
        appendDddCompliance(md, report.dddCompliancePercent(), report);

        // Hexagonal Compliance with port matrix
        appendHexagonalCompliance(md, report.hexCompliancePercent(), report.portMatrix());

        // Summary section
        md.append("## 6. Summary\n\n");
        md.append("| Metric | Count |\n");
        md.append("|--------|-------|\n");
        md.append("| Total Violations | ")
                .append(report.summary().totalViolations())
                .append(" |\n");
        md.append("| Blockers | ").append(report.summary().blockers()).append(" |\n");
        md.append("| Criticals | ").append(report.summary().criticals()).append(" |\n");
        md.append("| Majors | ").append(report.summary().majors()).append(" |\n");
        md.append("| Minors | ").append(report.summary().minors()).append(" |\n");
        md.append("| Infos | ").append(report.summary().infos()).append(" |\n\n");

        // Violations section
        md.append("## 7. Violations\n\n");
        if (report.violations().isEmpty()) {
            md.append("✅ **No violations found.**\n\n");
        } else {
            md.append("<details open>\n");
            md.append("<summary><strong>")
                    .append(report.violations().size())
                    .append(" violation(s) found</strong></summary>\n\n");

            md.append("| Severity | Constraint | Message | Affected Type | Location |\n");
            md.append("|----------|------------|---------|---------------|----------|\n");

            for (ViolationEntry v : report.violations()) {
                String emoji = getSeverityEmoji(v.severity());
                md.append("| ")
                        .append(emoji)
                        .append(" ")
                        .append(v.severity())
                        .append(" | `")
                        .append(v.constraintId())
                        .append("` | ")
                        .append(escapeMarkdown(v.message()))
                        .append(" | `")
                        .append(v.affectedType())
                        .append("` | `")
                        .append(v.location())
                        .append("` |\n");
            }

            md.append("\n</details>\n\n");
        }

        // Metrics section
        if (!report.metrics().isEmpty()) {
            md.append("## 8. Metrics\n\n");
            md.append("<details>\n");
            md.append("<summary><strong>")
                    .append(report.metrics().size())
                    .append(" metric(s) collected</strong></summary>\n\n");

            md.append("| Metric | Value | Threshold | Status |\n");
            md.append("|--------|-------|-----------|--------|\n");

            for (MetricEntry m : report.metrics()) {
                String statusEmoji = getStatusEmoji(m.status());
                md.append("| ")
                        .append(m.name())
                        .append(" | **")
                        .append(String.format("%.2f", m.value()))
                        .append("** ")
                        .append(m.unit())
                        .append(" | ");

                if (m.threshold() != null) {
                    md.append(m.thresholdType()).append(" ").append(String.format("%.2f", m.threshold()));
                } else {
                    md.append("-");
                }

                md.append(" | ")
                        .append(statusEmoji)
                        .append(" ")
                        .append(m.status())
                        .append(" |\n");
            }

            md.append("\n</details>\n\n");
        }

        // Constraints section
        if (report.constraints().totalConstraints() > 0) {
            md.append("## Constraints Evaluated\n\n");
            md.append("<details>\n");
            md.append("<summary><strong>")
                    .append(report.constraints().totalConstraints())
                    .append(" constraint(s) checked</strong></summary>\n\n");

            for (String constraintId : report.constraints().constraintNames()) {
                md.append("- `").append(constraintId).append("`\n");
            }

            md.append("\n</details>\n\n");
        }

        // Architecture Analysis section
        appendArchitectureAnalysis(md, report.architectureAnalysis());

        // Technical Debt
        appendTechnicalDebt(md, report.technicalDebt());

        // Recommendations
        appendRecommendations(md, report.recommendations());

        // Footer
        md.append("---\n\n");
        md.append("*Generated by HexaGlue Audit Plugin v")
                .append(report.metadata().hexaglueVersion())
                .append("*\n");

        return md.toString();
    }

    /**
     * Appends architecture analysis section to the Markdown output.
     */
    private void appendArchitectureAnalysis(StringBuilder md, ArchitectureAnalysis analysis) {
        if (analysis.isClean() && analysis.couplingMetrics().isEmpty()) {
            return; // Skip section if no interesting data
        }

        md.append("## 9. Architecture Analysis\n\n");

        // Summary
        if (analysis.isClean()) {
            md.append("✅ **No architecture issues detected.**\n\n");
        } else {
            md.append("| Issue Type | Count |\n");
            md.append("|------------|-------|\n");
            if (!analysis.typeCycles().isEmpty()) {
                md.append("| 🔄 Type Cycles | ")
                        .append(analysis.typeCycles().size())
                        .append(" |\n");
            }
            if (!analysis.packageCycles().isEmpty()) {
                md.append("| 📦 Package Cycles | ")
                        .append(analysis.packageCycles().size())
                        .append(" |\n");
            }
            if (!analysis.boundedContextCycles().isEmpty()) {
                md.append("| 🏗️ BC Cycles | ")
                        .append(analysis.boundedContextCycles().size())
                        .append(" |\n");
            }
            if (!analysis.layerViolations().isEmpty()) {
                md.append("| ⚠️ Layer Violations | ")
                        .append(analysis.layerViolations().size())
                        .append(" |\n");
            }
            if (!analysis.stabilityViolations().isEmpty()) {
                md.append("| ⚖️ Stability Violations | ")
                        .append(analysis.stabilityViolations().size())
                        .append(" |\n");
            }
            md.append("\n");
        }

        // Dependency Cycles
        if (!analysis.typeCycles().isEmpty() || !analysis.packageCycles().isEmpty()) {
            md.append("### Dependency Cycles\n\n");

            if (!analysis.typeCycles().isEmpty()) {
                md.append("<details>\n");
                md.append("<summary><strong>🔄 ")
                        .append(analysis.typeCycles().size())
                        .append(" Type-level cycle(s)</strong></summary>\n\n");
                for (var cycle : analysis.typeCycles()) {
                    md.append("- ");
                    md.append(String.join(" → ", cycle.path()));
                    md.append("\n");
                }
                md.append("\n</details>\n\n");
            }

            if (!analysis.packageCycles().isEmpty()) {
                md.append("<details>\n");
                md.append("<summary><strong>📦 ")
                        .append(analysis.packageCycles().size())
                        .append(" Package-level cycle(s)</strong></summary>\n\n");
                for (var cycle : analysis.packageCycles()) {
                    md.append("- ");
                    md.append(String.join(" → ", cycle.path()));
                    md.append("\n");
                }
                md.append("\n</details>\n\n");
            }
        }

        // Layer Violations
        if (!analysis.layerViolations().isEmpty()) {
            md.append("### Layer Violations\n\n");
            md.append("<details open>\n");
            md.append("<summary><strong>⚠️ ")
                    .append(analysis.layerViolations().size())
                    .append(" violation(s)</strong></summary>\n\n");
            md.append("| Source | Target | From Layer | To Layer | Description |\n");
            md.append("|--------|--------|------------|----------|-------------|\n");
            for (var v : analysis.layerViolations()) {
                md.append("| `")
                        .append(v.sourceType())
                        .append("` | `")
                        .append(v.targetType())
                        .append("` | ")
                        .append(v.sourceLayer())
                        .append(" | ")
                        .append(v.targetLayer())
                        .append(" | ")
                        .append(escapeMarkdown(v.description()))
                        .append(" |\n");
            }
            md.append("\n</details>\n\n");
        }

        // Stability Violations
        if (!analysis.stabilityViolations().isEmpty()) {
            md.append("### Stability Violations (SDP)\n\n");
            md.append("<details>\n");
            md.append("<summary><strong>⚖️ ")
                    .append(analysis.stabilityViolations().size())
                    .append(" violation(s)</strong></summary>\n\n");
            md.append("| Source | Target | Source I | Target I |\n");
            md.append("|--------|--------|----------|----------|\n");
            for (var v : analysis.stabilityViolations()) {
                md.append("| `")
                        .append(v.sourceType())
                        .append("` | `")
                        .append(v.targetType())
                        .append("` | ")
                        .append(String.format("%.2f", v.sourceStability()))
                        .append(" | ")
                        .append(String.format("%.2f", v.targetStability()))
                        .append(" |\n");
            }
            md.append("\n</details>\n\n");
        }

        // Package Coupling Metrics
        if (!analysis.couplingMetrics().isEmpty()) {
            md.append("### Package Coupling Metrics\n\n");
            md.append("<details>\n");
            md.append("<summary><strong>📊 ")
                    .append(analysis.couplingMetrics().size())
                    .append(" package(s) analyzed</strong></summary>\n\n");
            md.append("| Package | Ca | Ce | I | A | D | Zones |\n");
            md.append("|---------|----|----|---|---|---|-------|\n");
            for (var m : analysis.couplingMetrics()) {
                String zones = "";
                if (m.isInZoneOfPain()) zones = "🔥 Pain";
                if (m.isInZoneOfUselessness()) zones = "🚫 Useless";
                md.append("| `")
                        .append(m.packageName())
                        .append("` | ")
                        .append(m.afferentCoupling())
                        .append(" | ")
                        .append(m.efferentCoupling())
                        .append(" | ")
                        .append(String.format("%.2f", m.instability()))
                        .append(" | ")
                        .append(String.format("%.2f", m.abstractness()))
                        .append(" | ")
                        .append(String.format("%.2f", m.distance()))
                        .append(" | ")
                        .append(zones)
                        .append(" |\n");
            }
            md.append("\n*Ca=Afferent Coupling, Ce=Efferent Coupling, I=Instability, A=Abstractness, D=Distance*\n");
            md.append("\n</details>\n\n");
        }
    }

    /**
     * Returns an emoji for the given severity level.
     */
    private String getSeverityEmoji(String severity) {
        return switch (severity.toUpperCase()) {
            case "BLOCKER", "CRITICAL" -> "🔴";
            case "ERROR" -> "❌";
            case "MAJOR" -> "🟠";
            case "WARNING" -> "⚠️";
            case "MINOR" -> "🟡";
            case "INFO" -> "ℹ️";
            default -> "⚪";
        };
    }

    /**
     * Returns an emoji for the given status.
     */
    private String getStatusEmoji(String status) {
        return switch (status.toUpperCase()) {
            case "OK" -> "✅";
            case "WARNING" -> "⚠️";
            case "CRITICAL" -> "❌";
            default -> "⚪";
        };
    }

    /**
     * Escapes Markdown special characters.
     */
    private String escapeMarkdown(String s) {
        if (s == null) {
            return "";
        }
        // Escape pipe character which breaks tables
        return s.replace("|", "\\|");
    }

    /**
     * Appends the table of contents.
     */
    private void appendTableOfContents(StringBuilder md) {
        md.append("## Table of Contents\n\n");
        md.append("1. [Executive Summary](#1-executive-summary)\n");
        md.append("2. [Health Score](#2-health-score)\n");
        md.append("3. [Component Inventory](#3-component-inventory)\n");
        md.append("4. [DDD Compliance](#4-ddd-compliance)\n");
        md.append("5. [Hexagonal Compliance](#5-hexagonal-compliance)\n");
        md.append("6. [Summary](#6-summary)\n");
        md.append("7. [Violations](#7-violations)\n");
        md.append("8. [Metrics](#8-metrics)\n");
        md.append("9. [Architecture Analysis](#9-architecture-analysis)\n");
        md.append("10. [Technical Debt](#10-technical-debt)\n");
        md.append("11. [Recommendations](#11-recommendations)\n\n");
    }

    /**
     * Appends the executive summary section.
     */
    private void appendExecutiveSummary(StringBuilder md, ExecutiveSummary summary) {
        md.append("## 1. Executive Summary\n\n");

        // Verdict
        md.append("### Verdict\n\n");
        md.append(summary.verdict()).append("\n\n");

        // Strengths (table format)
        if (!summary.strengths().isEmpty()) {
            md.append("### Strengths\n\n");
            md.append("| Category | Observation |\n");
            md.append("|----------|-------------|\n");
            for (String strength : summary.strengths()) {
                String[] categoryAndObs = extractCategoryAndObservation(strength);
                md.append("| **").append(categoryAndObs[0]).append("** | ")
                        .append(categoryAndObs[1]).append(" |\n");
            }
            md.append("\n");
        }

        // Concerns
        if (!summary.concerns().isEmpty()) {
            md.append("### Concerns\n\n");
            md.append("| Severity | Description | Count |\n");
            md.append("|----------|-------------|-------|\n");
            for (var concern : summary.concerns()) {
                md.append("| ")
                        .append(concern.severity())
                        .append(" | ")
                        .append(concern.description())
                        .append(" | ")
                        .append(concern.count())
                        .append(" |\n");
            }
            md.append("\n");
        }

        // KPIs
        if (!summary.kpis().isEmpty()) {
            md.append("### Key Performance Indicators\n\n");
            md.append("| Indicator | Value | Threshold | Status |\n");
            md.append("|-----------|-------|-----------|--------|\n");
            for (var kpi : summary.kpis()) {
                String statusEmoji = getStatusEmoji(kpi.status());
                md.append("| ")
                        .append(kpi.name())
                        .append(" | ")
                        .append(kpi.value())
                        .append(" | ")
                        .append(kpi.threshold())
                        .append(" | ")
                        .append(statusEmoji)
                        .append(" ")
                        .append(kpi.status())
                        .append(" |\n");
            }
            md.append("\n");
        }

        // Immediate Actions
        if (!summary.immediateActions().isEmpty()) {
            md.append("### Immediate Actions\n\n");
            for (String action : summary.immediateActions()) {
                md.append("- ").append(action).append("\n");
            }
            md.append("\n");
        }
    }

    /**
     * Appends the health score section with Mermaid pie chart.
     */
    private void appendHealthScore(StringBuilder md, HealthScore score) {
        md.append("## 2. Health Score\n\n");

        md.append("**Overall Score: ")
                .append(score.overall())
                .append("/100 (Grade: ")
                .append(score.grade())
                .append(")**\n\n");

        // Mermaid pie chart for score distribution
        md.append("```mermaid\n");
        md.append("pie showData\n");
        md.append("    title Health Score Components\n");
        md.append("    \"DDD Compliance (25%)\" : ").append(score.dddCompliance()).append("\n");
        md.append("    \"Hexagonal (25%)\" : ").append(score.hexCompliance()).append("\n");
        md.append("    \"Dependencies (20%)\" : ").append(score.dependencyQuality()).append("\n");
        md.append("    \"Coupling (15%)\" : ").append(score.coupling()).append("\n");
        md.append("    \"Cohesion (15%)\" : ").append(score.cohesion()).append("\n");
        md.append("```\n\n");

        // Score breakdown table
        md.append("| Component | Score | Weight |\n");
        md.append("|-----------|-------|--------|\n");
        md.append("| DDD Compliance | ").append(score.dddCompliance()).append("% | 25% |\n");
        md.append("| Hexagonal Compliance | ").append(score.hexCompliance()).append("% | 25% |\n");
        md.append("| Dependency Quality | ").append(score.dependencyQuality()).append("% | 20% |\n");
        md.append("| Coupling Quality | ").append(score.coupling()).append("% | 15% |\n");
        md.append("| Cohesion Quality | ").append(score.cohesion()).append("% | 15% |\n\n");
    }

    /**
     * Appends the component inventory section with Mermaid chart.
     */
    private void appendComponentInventory(StringBuilder md, ComponentInventory inventory) {
        md.append("## 3. Component Inventory\n\n");

        // Mermaid bar chart
        md.append("```mermaid\n");
        md.append("xychart-beta\n");
        md.append("    title \"Domain Model Components\"\n");
        md.append("    x-axis [\"Aggregates\", \"Entities\", \"ValueObjects\", \"Events\", \"DomainSvc\", \"AppSvc\"]\n");
        int maxY = Math.max(10, Math.max(inventory.aggregateRoots(),
                Math.max(inventory.entities(),
                        Math.max(inventory.valueObjects(),
                                Math.max(inventory.domainEvents(),
                                        Math.max(inventory.domainServices(), inventory.applicationServices()))))));
        md.append("    y-axis \"Count\" 0 --> ").append(maxY + 2).append("\n");
        md.append("    bar [")
                .append(inventory.aggregateRoots())
                .append(", ")
                .append(inventory.entities())
                .append(", ")
                .append(inventory.valueObjects())
                .append(", ")
                .append(inventory.domainEvents())
                .append(", ")
                .append(inventory.domainServices())
                .append(", ")
                .append(inventory.applicationServices())
                .append("]\n");
        md.append("```\n\n");

        // Domain Model table
        md.append("### Domain Model\n\n");
        md.append("| Type | Count |\n");
        md.append("|------|-------|\n");
        md.append("| Aggregate Roots | ").append(inventory.aggregateRoots()).append(" |\n");
        md.append("| Entities | ").append(inventory.entities()).append(" |\n");
        md.append("| Value Objects | ").append(inventory.valueObjects()).append(" |\n");
        md.append("| Domain Events | ").append(inventory.domainEvents()).append(" |\n");
        md.append("| Domain Services | ").append(inventory.domainServices()).append(" |\n");
        md.append("| Application Services | ").append(inventory.applicationServices()).append(" |\n");
        md.append("| **Total Domain Types** | **").append(inventory.totalDomainTypes()).append("** |\n\n");

        // Ports table
        md.append("### Ports\n\n");
        md.append("| Direction | Count |\n");
        md.append("|-----------|-------|\n");
        md.append("| Driving (Inbound) | ").append(inventory.drivingPorts()).append(" |\n");
        md.append("| Driven (Outbound) | ").append(inventory.drivenPorts()).append(" |\n");
        md.append("| **Total Ports** | **").append(inventory.totalPorts()).append("** |\n\n");
    }

    /**
     * Appends the DDD compliance section.
     */
    private void appendDddCompliance(StringBuilder md, int dddCompliancePercent, AuditReport report) {
        md.append("## 4. DDD Compliance\n\n");
        md.append("**Score: ").append(dddCompliancePercent).append("%**\n\n");

        // Filter DDD-related violations
        var dddViolations = report.violations().stream()
                .filter(v -> v.constraintId().startsWith("ddd:"))
                .toList();

        if (dddViolations.isEmpty()) {
            md.append("✅ No DDD constraint violations detected.\n\n");
        } else {
            md.append("| Constraint | Count | Description |\n");
            md.append("|------------|-------|-------------|\n");

            // Group by constraint ID
            var byConstraint = dddViolations.stream()
                    .collect(java.util.stream.Collectors.groupingBy(ViolationEntry::constraintId));
            for (var entry : byConstraint.entrySet()) {
                md.append("| `")
                        .append(entry.getKey())
                        .append("` | ")
                        .append(entry.getValue().size())
                        .append(" | ")
                        .append(escapeMarkdown(entry.getValue().get(0).message()))
                        .append(" |\n");
            }
            md.append("\n");
        }
    }

    /**
     * Appends the hexagonal compliance section with port matrix.
     */
    private void appendHexagonalCompliance(StringBuilder md, int hexCompliancePercent, java.util.List<PortMatrixEntry> portMatrix) {
        md.append("## 5. Hexagonal Compliance\n\n");
        md.append("**Score: ").append(hexCompliancePercent).append("%**\n\n");

        // Port Matrix
        if (!portMatrix.isEmpty()) {
            md.append("### Port Matrix\n\n");
            md.append("| Port | Direction | Kind | Managed Type | Methods | Adapter |\n");
            md.append("|------|-----------|------|--------------|---------|--------|\n");
            for (var port : portMatrix) {
                String adapterStatus = port.hasAdapter() ? "✅" : "❌";
                md.append("| `")
                        .append(port.portName())
                        .append("` | ")
                        .append(port.direction())
                        .append(" | ")
                        .append(port.kind())
                        .append(" | ")
                        .append(port.managedType() != null ? "`" + port.managedType() + "`" : "-")
                        .append(" | ")
                        .append(port.methodCount())
                        .append(" | ")
                        .append(adapterStatus)
                        .append(" |\n");
            }
            md.append("\n");
        }
    }

    /**
     * Appends the technical debt section.
     */
    private void appendTechnicalDebt(StringBuilder md, TechnicalDebtSummary debt) {
        md.append("## 10. Technical Debt\n\n");

        if (debt.isZero()) {
            md.append("✅ **No technical debt detected.**\n\n");
            return;
        }

        // Summary
        md.append("| Metric | Value |\n");
        md.append("|--------|-------|\n");
        md.append("| Total Effort | **")
                .append(String.format("%.1f", debt.totalDays()))
                .append(" person-days** |\n");
        md.append("| Total Cost | **")
                .append(String.format("%.2f €", debt.totalCost()))
                .append("** |\n");
        md.append("| Monthly Interest | ")
                .append(String.format("%.2f €", debt.monthlyInterest()))
                .append(" |\n\n");

        // Breakdown by category
        if (!debt.breakdown().isEmpty()) {
            md.append("### Breakdown by Category\n\n");
            md.append("| Category | Days | Cost | Description |\n");
            md.append("|----------|------|------|-------------|\n");
            for (var cat : debt.breakdown()) {
                md.append("| ")
                        .append(cat.category())
                        .append(" | ")
                        .append(String.format("%.1f", cat.days()))
                        .append(" | ")
                        .append(String.format("%.2f €", cat.cost()))
                        .append(" | ")
                        .append(escapeMarkdown(cat.description()))
                        .append(" |\n");
            }
            md.append("\n");
        }
    }

    /**
     * Appends the recommendations section.
     */
    private void appendRecommendations(StringBuilder md, java.util.List<Recommendation> recommendations) {
        md.append("## 11. Recommendations\n\n");

        if (recommendations.isEmpty()) {
            md.append("✅ **No specific recommendations - the architecture is in good shape!**\n\n");
            return;
        }

        md.append("| Priority | Title | Effort | Impact |\n");
        md.append("|----------|-------|--------|--------|\n");
        for (var rec : recommendations) {
            String priorityEmoji = getPriorityEmoji(rec.priority().name());
            md.append("| ")
                    .append(priorityEmoji)
                    .append(" ")
                    .append(rec.priority())
                    .append(" | ")
                    .append(escapeMarkdown(rec.title()))
                    .append(" | ")
                    .append(String.format("%.1f days", rec.estimatedEffort()))
                    .append(" | ")
                    .append(escapeMarkdown(rec.expectedImpact()))
                    .append(" |\n");
        }
        md.append("\n");

        // Details
        md.append("<details>\n");
        md.append("<summary><strong>Recommendation Details</strong></summary>\n\n");
        for (var rec : recommendations) {
            md.append("### ").append(rec.title()).append("\n\n");
            md.append("**Priority:** ").append(rec.priority()).append("  \n");
            md.append("**Estimated Effort:** ").append(String.format("%.1f days", rec.estimatedEffort())).append("  \n");
            md.append("**Expected Impact:** ").append(rec.expectedImpact()).append("\n\n");
            md.append(rec.description()).append("\n\n");
            if (!rec.affectedTypes().isEmpty()) {
                md.append("**Affected Types:**\n");
                for (String type : rec.affectedTypes()) {
                    md.append("- `").append(type).append("`\n");
                }
                md.append("\n");
            }
        }
        md.append("</details>\n\n");
    }

    /**
     * Returns an emoji for the recommendation priority.
     */
    private String getPriorityEmoji(String priority) {
        return switch (priority.toUpperCase()) {
            case "IMMEDIATE" -> "🔴";
            case "SHORT_TERM" -> "🟠";
            case "MEDIUM_TERM" -> "🟡";
            case "LOW" -> "🟢";
            default -> "⚪";
        };
    }

    /**
     * Extracts a category and observation from a strength description.
     *
     * <p>Parses strength strings to extract meaningful categories like
     * "Domain Model", "Architecture", "Ports", "Cohesion", etc.
     *
     * @param strength the strength description
     * @return array with [category, observation]
     */
    private String[] extractCategoryAndObservation(String strength) {
        String lowerStrength = strength.toLowerCase();

        // DDD patterns
        if (lowerStrength.contains("ddd") || lowerStrength.contains("domain-driven")) {
            return new String[]{"DDD Patterns", strength};
        }
        if (lowerStrength.contains("domain model") || lowerStrength.contains("value object")) {
            return new String[]{"Domain Model", strength};
        }
        if (lowerStrength.contains("aggregate")) {
            return new String[]{"Aggregates", strength};
        }

        // Hexagonal architecture
        if (lowerStrength.contains("hexagonal")) {
            return new String[]{"Hexagonal Architecture", strength};
        }
        if (lowerStrength.contains("port")) {
            return new String[]{"Ports", strength};
        }

        // Architecture quality
        if (lowerStrength.contains("cycle") || lowerStrength.contains("layer violation")) {
            return new String[]{"Architecture", strength};
        }
        if (lowerStrength.contains("cohesion")) {
            return new String[]{"Cohesion", strength};
        }
        if (lowerStrength.contains("coupling")) {
            return new String[]{"Coupling", strength};
        }
        if (lowerStrength.contains("dependency")) {
            return new String[]{"Dependencies", strength};
        }

        // Default
        return new String[]{"General", strength};
    }
}
