/*
 * This Source Code Form is part of the HexaGlue project.
 * Copyright (c) 2026 Scalastic
 *
 * This Source Code Form is subject to the terms of the Mozilla Public
 * License, v. 2.0. If a copy of the MPL was not distributed with this
 * file, You can obtain one at https://mozilla.org/MPL/2.0/.
 *
 * Commercial licensing options are available for organizations wishing
 * to use HexaGlue under terms different from the MPL 2.0.
 * Contact: info@hexaglue.io
 */

package io.hexaglue.plugin.audit.adapter.report;

import io.hexaglue.plugin.audit.adapter.diagram.C4DiagramBuilder;
import io.hexaglue.plugin.audit.adapter.report.model.ArchitectureAnalysis;
import io.hexaglue.plugin.audit.adapter.report.model.AuditReport;
import io.hexaglue.plugin.audit.adapter.report.model.ComponentInventory;
import io.hexaglue.plugin.audit.adapter.report.model.ExecutiveSummary;
import io.hexaglue.plugin.audit.adapter.report.model.HealthScore;
import io.hexaglue.plugin.audit.adapter.report.model.MetricEntry;
import io.hexaglue.plugin.audit.adapter.report.model.PortMatrixEntry;
import io.hexaglue.plugin.audit.adapter.report.model.TechnicalDebtSummary;
import io.hexaglue.plugin.audit.adapter.report.model.ViolationEntry;
import io.hexaglue.plugin.audit.domain.model.Recommendation;
import io.hexaglue.spi.audit.DetectedArchitectureStyle;
import java.time.ZoneId;
import java.time.format.DateTimeFormatter;
import java.util.List;
import java.util.Map;
import java.util.Objects;

/**
 * Generates audit reports in GitHub-flavored Markdown format.
 *
 * <p>This generator produces Markdown that renders well on GitHub and other
 * Markdown viewers. Features include:
 * <ul>
 *   <li>Emoji indicators for status (pass/fail)</li>
 *   <li>Tables for violations and metrics</li>
 *   <li>Collapsible sections using HTML details tags</li>
 *   <li>Code formatting for technical details</li>
 * </ul>
 *
 * @since 1.0.0
 */
public final class MarkdownReportGenerator implements ReportGenerator {

    private static final DateTimeFormatter TIMESTAMP_FORMATTER = DateTimeFormatter.ofPattern("yyyy-MM-dd HH:mm:ss");

    @Override
    public ReportFormat format() {
        return ReportFormat.MARKDOWN;
    }

    @Override
    public String generate(AuditReport report) {
        Objects.requireNonNull(report, "report required");

        StringBuilder md = new StringBuilder();
        SectionNumbering numbering = SectionNumbering.create();

        // Title
        md.append("# HexaGlue Architecture Audit Report\n\n");

        // Metadata
        md.append("**Application**: ").append(report.metadata().projectName()).append("  \n");
        md.append("**Analyzed Version**: ")
                .append(report.metadata().projectVersion())
                .append("  \n");
        md.append("**Audit Date**: ")
                .append(TIMESTAMP_FORMATTER.format(report.metadata().timestamp().atZone(ZoneId.systemDefault())))
                .append("  \n");
        md.append("**Duration**: ").append(report.metadata().duration()).append("  \n");
        md.append("**Generated by**: HexaGlue AuditPlugin v")
                .append(report.metadata().hexaglueVersion())
                .append("  \n\n");

        // Separator
        md.append("---\n\n");

        // Compliance Summary in blockquote
        String statusIcon = report.summary().passed() ? "✅ PASSED" : "❌ FAILED";
        md.append("> ## 🛡️ Compliance Summary\n>\n");
        md.append("> | Global Status | Health Score | DDD Compliance | Hexagonal Compliance |\n");
        md.append("> |:-------------:|:------------:|:--------------:|:--------------------:|\n");
        md.append("> | **")
                .append(statusIcon)
                .append("** | **")
                .append(report.healthScore().overall())
                .append("/100 (")
                .append(report.healthScore().grade())
                .append(")** | **")
                .append(report.dddCompliancePercent())
                .append("%** | **")
                .append(report.hexCompliancePercent())
                .append("%** |\n\n");

        // Table of Contents
        appendTableOfContents(md);

        // Executive Summary
        appendExecutiveSummary(md, report.executiveSummary(), numbering);

        // Health Score
        appendHealthScore(md, report.healthScore(), numbering);

        // Architecture Overview (Component Inventory + Bounded Contexts + Architecture Diagram + C4)
        appendComponentInventory(md, report, numbering);

        // DDD Compliance
        appendDddCompliance(md, report.dddCompliancePercent(), report, numbering);

        // Hexagonal Compliance with port matrix
        appendHexagonalCompliance(md, report.hexCompliancePercent(), report.portMatrix(), numbering);

        // Summary section
        md.append(numbering.h2("Summary")).append("\n\n");
        md.append("| Metric | Count |\n");
        md.append("|--------|-------|\n");
        md.append("| Total Violations | ")
                .append(report.summary().totalViolations())
                .append(" |\n");
        md.append("| Blockers | ").append(report.summary().blockers()).append(" |\n");
        md.append("| Criticals | ").append(report.summary().criticals()).append(" |\n");
        md.append("| Majors | ").append(report.summary().majors()).append(" |\n");
        md.append("| Minors | ").append(report.summary().minors()).append(" |\n");
        md.append("| Infos | ").append(report.summary().infos()).append(" |\n\n");

        // Violations section
        md.append(numbering.h2("Violations")).append("\n\n");
        if (report.violations().isEmpty()) {
            md.append("✅ **No violations found.**\n\n");
        } else {
            md.append("<details open>\n");
            md.append("<summary><strong>")
                    .append(report.violations().size())
                    .append(" violation(s) found</strong></summary>\n\n");

            md.append("| Severity | Constraint | Message | Affected Type | Location |\n");
            md.append("|----------|------------|---------|---------------|----------|\n");

            for (ViolationEntry v : report.violations()) {
                String emoji = getSeverityEmoji(v.severity());
                md.append("| ")
                        .append(emoji)
                        .append(" ")
                        .append(v.severity())
                        .append(" | `")
                        .append(v.constraintId())
                        .append("` | ")
                        .append(escapeMarkdown(v.message()))
                        .append(" | `")
                        .append(v.affectedType())
                        .append("` | `")
                        .append(v.location())
                        .append("` |\n");
            }

            md.append("\n</details>\n\n");
        }

        // Metrics section
        if (!report.metrics().isEmpty()) {
            md.append(numbering.h2("Metrics")).append("\n\n");
            md.append("<details>\n");
            md.append("<summary><strong>")
                    .append(report.metrics().size())
                    .append(" metric(s) collected</strong></summary>\n\n");

            md.append("| Metric | Value | Threshold | Status |\n");
            md.append("|--------|-------|-----------|--------|\n");

            for (MetricEntry m : report.metrics()) {
                String statusEmoji = getStatusEmoji(m.status());
                md.append("| ")
                        .append(m.name())
                        .append(" | **")
                        .append(String.format("%.2f", m.value()))
                        .append("** ")
                        .append(m.unit())
                        .append(" | ");

                if (m.threshold() != null) {
                    md.append(m.thresholdType()).append(" ").append(String.format("%.2f", m.threshold()));
                } else {
                    md.append("-");
                }

                md.append(" | ")
                        .append(statusEmoji)
                        .append(" ")
                        .append(m.status())
                        .append(" |\n");
            }

            md.append("\n</details>\n\n");
        }

        // Constraints section
        if (report.constraints().totalConstraints() > 0) {
            md.append(numbering.h2("Constraints Evaluated")).append("\n\n");
            md.append("<details>\n");
            md.append("<summary><strong>")
                    .append(report.constraints().totalConstraints())
                    .append(" constraint(s) checked</strong></summary>\n\n");

            for (String constraintId : report.constraints().constraintNames()) {
                md.append("- `").append(constraintId).append("`\n");
            }

            md.append("\n</details>\n\n");
        }

        // Architecture Analysis section
        appendArchitectureAnalysis(md, report.architectureAnalysis(), numbering);

        // Technical Debt
        appendTechnicalDebt(md, report.technicalDebt(), numbering);

        // Recommendations
        appendRecommendations(md, report.recommendations(), numbering);

        // Footer
        md.append("---\n\n");
        md.append("*Generated by HexaGlue Audit Plugin v")
                .append(report.metadata().hexaglueVersion())
                .append("*\n");

        return md.toString();
    }

    /**
     * Appends architecture analysis section to the Markdown output.
     */
    private void appendArchitectureAnalysis(
            StringBuilder md, ArchitectureAnalysis analysis, SectionNumbering numbering) {
        if (analysis.isClean() && analysis.couplingMetrics().isEmpty()) {
            return; // Skip section if no interesting data
        }

        md.append(numbering.h2("Architecture Analysis")).append("\n\n");

        // Summary
        if (analysis.isClean()) {
            md.append("✅ **No architecture issues detected.**\n\n");
        } else {
            md.append("| Issue Type | Count |\n");
            md.append("|------------|-------|\n");
            if (!analysis.typeCycles().isEmpty()) {
                md.append("| 🔄 Type Cycles | ")
                        .append(analysis.typeCycles().size())
                        .append(" |\n");
            }
            if (!analysis.packageCycles().isEmpty()) {
                md.append("| 📦 Package Cycles | ")
                        .append(analysis.packageCycles().size())
                        .append(" |\n");
            }
            if (!analysis.boundedContextCycles().isEmpty()) {
                md.append("| 🏗️ BC Cycles | ")
                        .append(analysis.boundedContextCycles().size())
                        .append(" |\n");
            }
            if (!analysis.layerViolations().isEmpty()) {
                md.append("| ⚠️ Layer Violations | ")
                        .append(analysis.layerViolations().size())
                        .append(" |\n");
            }
            if (!analysis.stabilityViolations().isEmpty()) {
                md.append("| ⚖️ Stability Violations | ")
                        .append(analysis.stabilityViolations().size())
                        .append(" |\n");
            }
            md.append("\n");
        }

        // Dependency Cycles
        if (!analysis.typeCycles().isEmpty() || !analysis.packageCycles().isEmpty()) {
            md.append(numbering.h3("Dependency Cycles")).append("\n\n");

            if (!analysis.typeCycles().isEmpty()) {
                md.append("<details>\n");
                md.append("<summary><strong>🔄 ")
                        .append(analysis.typeCycles().size())
                        .append(" Type-level cycle(s)</strong></summary>\n\n");
                for (var cycle : analysis.typeCycles()) {
                    md.append("- ");
                    md.append(String.join(" → ", cycle.path()));
                    md.append("\n");
                }
                md.append("\n</details>\n\n");
            }

            if (!analysis.packageCycles().isEmpty()) {
                md.append("<details>\n");
                md.append("<summary><strong>📦 ")
                        .append(analysis.packageCycles().size())
                        .append(" Package-level cycle(s)</strong></summary>\n\n");
                for (var cycle : analysis.packageCycles()) {
                    md.append("- ");
                    md.append(String.join(" → ", cycle.path()));
                    md.append("\n");
                }
                md.append("\n</details>\n\n");
            }
        }

        // Layer Violations
        if (!analysis.layerViolations().isEmpty()) {
            md.append(numbering.h3("Layer Violations")).append("\n\n");
            md.append("<details open>\n");
            md.append("<summary><strong>⚠️ ")
                    .append(analysis.layerViolations().size())
                    .append(" violation(s)</strong></summary>\n\n");
            md.append("| Source | Target | From Layer | To Layer | Description |\n");
            md.append("|--------|--------|------------|----------|-------------|\n");
            for (var v : analysis.layerViolations()) {
                md.append("| `")
                        .append(v.sourceType())
                        .append("` | `")
                        .append(v.targetType())
                        .append("` | ")
                        .append(v.sourceLayer())
                        .append(" | ")
                        .append(v.targetLayer())
                        .append(" | ")
                        .append(escapeMarkdown(v.description()))
                        .append(" |\n");
            }
            md.append("\n</details>\n\n");
        }

        // Stability Violations
        if (!analysis.stabilityViolations().isEmpty()) {
            md.append(numbering.h3("Stability Violations (SDP)")).append("\n\n");
            md.append("<details>\n");
            md.append("<summary><strong>⚖️ ")
                    .append(analysis.stabilityViolations().size())
                    .append(" violation(s)</strong></summary>\n\n");
            md.append("| Source | Target | Source I | Target I |\n");
            md.append("|--------|--------|----------|----------|\n");
            for (var v : analysis.stabilityViolations()) {
                md.append("| `")
                        .append(v.sourceType())
                        .append("` | `")
                        .append(v.targetType())
                        .append("` | ")
                        .append(String.format("%.2f", v.sourceStability()))
                        .append(" | ")
                        .append(String.format("%.2f", v.targetStability()))
                        .append(" |\n");
            }
            md.append("\n</details>\n\n");
        }

        // Package Coupling Metrics
        if (!analysis.couplingMetrics().isEmpty()) {
            md.append(numbering.h3("Package Coupling Metrics")).append("\n\n");
            md.append("<details>\n");
            md.append("<summary><strong>📊 ")
                    .append(analysis.couplingMetrics().size())
                    .append(" package(s) analyzed</strong></summary>\n\n");
            md.append("| Package | Ca | Ce | I | A | D | Zones |\n");
            md.append("|---------|----|----|---|---|---|-------|\n");
            for (var m : analysis.couplingMetrics()) {
                String zones = "";
                if (m.isInZoneOfPain()) zones = "🔥 Pain";
                if (m.isInZoneOfUselessness()) zones = "🚫 Useless";
                md.append("| `")
                        .append(m.packageName())
                        .append("` | ")
                        .append(m.afferentCoupling())
                        .append(" | ")
                        .append(m.efferentCoupling())
                        .append(" | ")
                        .append(String.format("%.2f", m.instability()))
                        .append(" | ")
                        .append(String.format("%.2f", m.abstractness()))
                        .append(" | ")
                        .append(String.format("%.2f", m.distance()))
                        .append(" | ")
                        .append(zones)
                        .append(" |\n");
            }
            md.append("\n*Ca=Afferent Coupling, Ce=Efferent Coupling, I=Instability, A=Abstractness, D=Distance*\n");
            md.append("\n</details>\n\n");
        }
    }

    /**
     * Returns an emoji for the given severity level.
     */
    private String getSeverityEmoji(String severity) {
        return switch (severity.toUpperCase()) {
            case "BLOCKER", "CRITICAL" -> "🔴";
            case "ERROR" -> "❌";
            case "MAJOR" -> "🟠";
            case "WARNING" -> "⚠️";
            case "MINOR" -> "🟡";
            case "INFO" -> "ℹ️";
            default -> "⚪";
        };
    }

    /**
     * Returns an emoji for the given status.
     */
    private String getStatusEmoji(String status) {
        return switch (status.toUpperCase()) {
            case "OK" -> "✅";
            case "WARNING" -> "⚠️";
            case "CRITICAL" -> "❌";
            default -> "⚪";
        };
    }

    /**
     * Escapes Markdown special characters.
     */
    private String escapeMarkdown(String s) {
        if (s == null) {
            return "";
        }
        // Escape pipe character which breaks tables
        return s.replace("|", "\\|");
    }

    /**
     * Appends the table of contents.
     */
    private void appendTableOfContents(StringBuilder md) {
        md.append("## Table of Contents\n\n");
        md.append("1. [Executive Summary](#1-executive-summary)\n");
        md.append("2. [Architectural Health Score](#2-architectural-health-score)\n");
        md.append("3. [Architecture Overview](#3-architecture-overview)\n");
        md.append("4. [Domain-Driven Design Compliance](#4-domain-driven-design-compliance)\n");
        md.append("5. [Hexagonal Compliance](#5-hexagonal-compliance)\n");
        md.append("6. [Summary](#6-summary)\n");
        md.append("7. [Violations](#7-violations)\n");
        md.append("8. [Metrics](#8-metrics)\n");
        md.append("9. [Architecture Analysis](#9-architecture-analysis)\n");
        md.append("10. [Technical Debt](#10-technical-debt)\n");
        md.append("11. [Recommendations](#11-recommendations)\n\n");
    }

    /**
     * Appends the executive summary section.
     */
    private void appendExecutiveSummary(StringBuilder md, ExecutiveSummary summary, SectionNumbering numbering) {
        md.append(numbering.h2("Executive Summary")).append("\n\n");

        // Verdict
        md.append(numbering.h3("Verdict")).append("\n\n");
        md.append(summary.verdict()).append("\n\n");

        // Strengths (table format)
        if (!summary.strengths().isEmpty()) {
            md.append(numbering.h3("Strengths")).append("\n\n");
            md.append("| Category | Observation |\n");
            md.append("|----------|-------------|\n");
            for (String strength : summary.strengths()) {
                String[] categoryAndObs = extractCategoryAndObservation(strength);
                md.append("| **")
                        .append(categoryAndObs[0])
                        .append("** | ")
                        .append(categoryAndObs[1])
                        .append(" |\n");
            }
            md.append("\n");
        }

        // Concerns
        if (!summary.concerns().isEmpty()) {
            md.append(numbering.h3("Concerns")).append("\n\n");
            md.append("| Severity | Description | Count |\n");
            md.append("|----------|-------------|-------|\n");
            for (var concern : summary.concerns()) {
                md.append("| ")
                        .append(concern.severity())
                        .append(" | ")
                        .append(concern.description())
                        .append(" | ")
                        .append(concern.count())
                        .append(" |\n");
            }
            md.append("\n");
        }

        // KPIs
        if (!summary.kpis().isEmpty()) {
            md.append(numbering.h3("Key Performance Indicators (KPIs)")).append("\n\n");
            md.append("| Indicator | Value | Threshold | Status |\n");
            md.append("|-----------|-------|-----------|--------|\n");
            for (var kpi : summary.kpis()) {
                String statusEmoji = getStatusEmoji(kpi.status());
                md.append("| ")
                        .append(kpi.name())
                        .append(" | ")
                        .append(kpi.value())
                        .append(" | ")
                        .append(kpi.threshold())
                        .append(" | ")
                        .append(statusEmoji)
                        .append(" ")
                        .append(kpi.status())
                        .append(" |\n");
            }
            md.append("\n");
        }

        // Immediate Actions
        if (!summary.immediateActions().isEmpty()) {
            md.append(numbering.h3("Immediate Actions Required")).append("\n\n");
            for (String action : summary.immediateActions()) {
                md.append("- ").append(action).append("\n");
            }
            md.append("\n");
        }
    }

    /**
     * Appends the health score section with Mermaid radar chart.
     */
    private void appendHealthScore(StringBuilder md, HealthScore score, SectionNumbering numbering) {
        md.append(numbering.h2("Architectural Health Score")).append("\n\n");

        md.append(numbering.h3("Overall Score: " + score.overall() + "/100 (" + score.grade() + " grade)"))
                .append("\n\n");

        // Mermaid radar chart for score visualization
        md.append("```mermaid\n");
        md.append("---\n");
        md.append("config:\n");
        md.append("  look: neo\n");
        md.append("  theme: forest\n");
        md.append("---\n");
        md.append("radar-beta\n");
        md.append("    title Health Score Components\n");
        md.append("    max 100\n");
        md.append(
                "    axis ddd[\"DDD (25%)\"], hex[\"Hexagonal (25%)\"], dep[\"Dependencies (20%)\"], cpl[\"Coupling (15%)\"], coh[\"Cohesion (15%)\"]\n");
        md.append("    curve Score{")
                .append(score.dddCompliance())
                .append(", ")
                .append(score.hexCompliance())
                .append(", ")
                .append(score.dependencyQuality())
                .append(", ")
                .append(score.coupling())
                .append(", ")
                .append(score.cohesion())
                .append("}\n");
        md.append("```\n\n");

        // Score breakdown subsection
        md.append(numbering.h3("Score Breakdown")).append("\n\n");

        // Calculate contributions
        double dddContrib = score.dddCompliance() * 0.25;
        double hexContrib = score.hexCompliance() * 0.25;
        double depContrib = score.dependencyQuality() * 0.20;
        double cplContrib = score.coupling() * 0.15;
        double cohContrib = score.cohesion() * 0.15;
        double total = dddContrib + hexContrib + depContrib + cplContrib + cohContrib;

        md.append("| Dimension | Weight | Score | Contribution |\n");
        md.append("|-----------|:------:|:-----:|:------------:|\n");
        md.append("| **DDD Compliance** | 25% | ")
                .append(score.dddCompliance())
                .append("/100 | ")
                .append(String.format("%.2f", dddContrib))
                .append(" |\n");
        md.append("| **Hexagonal Compliance** | 25% | ")
                .append(score.hexCompliance())
                .append("/100 | ")
                .append(String.format("%.2f", hexContrib))
                .append(" |\n");
        md.append("| **Dependency Quality** | 20% | ")
                .append(score.dependencyQuality())
                .append("/100 | ")
                .append(String.format("%.2f", depContrib))
                .append(" |\n");
        md.append("| **Coupling Metrics** | 15% | ")
                .append(score.coupling())
                .append("/100 | ")
                .append(String.format("%.2f", cplContrib))
                .append(" |\n");
        md.append("| **Domain Cohesion** | 15% | ")
                .append(score.cohesion())
                .append("/100 | ")
                .append(String.format("%.2f", cohContrib))
                .append(" |\n");
        md.append("| **TOTAL** | 100% | – | **")
                .append(String.format("%.2f", total))
                .append("** |\n\n");
    }

    /**
     * Appends the architecture overview section with component inventory, bounded context breakdown,
     * architectural style diagram, and C4 model diagrams.
     */
    private void appendComponentInventory(StringBuilder md, AuditReport report, SectionNumbering numbering) {
        ComponentInventory inventory = report.inventory();
        DetectedArchitectureStyle style = report.detectedStyle();

        md.append(numbering.h2("Architecture Overview")).append("\n\n");

        // 3.1 Component Inventory
        md.append(numbering.h3("Component Inventory")).append("\n\n");
        md.append("| Category | Count | Details |\n");
        md.append("|----------|:-----:|--------|\n");

        // Bounded Contexts count
        int bcCount = inventory.boundedContexts().size();
        String bcNames = inventory.boundedContexts().stream()
                .map(bc -> bc.name())
                .limit(4)
                .collect(java.util.stream.Collectors.joining(", "));
        if (bcCount > 4) {
            bcNames += ", ...";
        }
        md.append("| **Bounded Contexts** | ")
                .append(bcCount)
                .append(" | ")
                .append(bcNames.isEmpty() ? "–" : bcNames)
                .append(" |\n");

        // Domain types with examples
        md.append("| **Aggregate Roots** | ")
                .append(inventory.aggregateRoots())
                .append(" | ")
                .append(ComponentInventory.formatExamples(inventory.aggregateExamples(), inventory.aggregateRoots()))
                .append(" |\n");
        md.append("| **Entities** | ")
                .append(inventory.entities())
                .append(" | ")
                .append(ComponentInventory.formatExamples(inventory.entityExamples(), inventory.entities()))
                .append(" |\n");
        md.append("| **Value Objects** | ")
                .append(inventory.valueObjects())
                .append(" | ")
                .append(ComponentInventory.formatExamples(inventory.valueObjectExamples(), inventory.valueObjects()))
                .append(" |\n");
        md.append("| **Domain Services** | ")
                .append(inventory.domainServices())
                .append(" | ")
                .append(ComponentInventory.formatExamples(
                        inventory.domainServiceExamples(), inventory.domainServices()))
                .append(" |\n");
        md.append("| **Domain Events** | ")
                .append(inventory.domainEvents())
                .append(" | ")
                .append(ComponentInventory.formatExamples(inventory.domainEventExamples(), inventory.domainEvents()))
                .append(" |\n");

        // Ports with examples
        md.append("| **Ports (Driving)** | ")
                .append(inventory.drivingPorts())
                .append(" | ")
                .append(ComponentInventory.formatExamples(inventory.drivingPortExamples(), inventory.drivingPorts()))
                .append(" |\n");
        md.append("| **Ports (Driven)** | ")
                .append(inventory.drivenPorts())
                .append(" | ")
                .append(ComponentInventory.formatExamples(inventory.drivenPortExamples(), inventory.drivenPorts()))
                .append(" |\n\n");

        // 3.2 Breakdown by Bounded Context
        if (!inventory.boundedContexts().isEmpty()) {
            md.append(numbering.h3("Breakdown by Bounded Context")).append("\n\n");
            md.append("| Bounded Context | Aggregates | Entities | VOs | Ports | LOC |\n");
            md.append("|-----------------|:----------:|:--------:|:---:|:-----:|----:|\n");

            int totalAgg = 0, totalEnt = 0, totalVo = 0, totalPorts = 0, totalLoc = 0;
            for (var bc : inventory.boundedContexts()) {
                md.append("| **")
                        .append(bc.name())
                        .append("** | ")
                        .append(bc.aggregates())
                        .append(" | ")
                        .append(bc.entities())
                        .append(" | ")
                        .append(bc.valueObjects())
                        .append(" | ")
                        .append(bc.ports())
                        .append(" | ")
                        .append(formatLoc(bc.estimatedLoc()))
                        .append(" |\n");
                totalAgg += bc.aggregates();
                totalEnt += bc.entities();
                totalVo += bc.valueObjects();
                totalPorts += bc.ports();
                totalLoc += bc.estimatedLoc();
            }
            md.append("| **TOTAL** | ")
                    .append(totalAgg)
                    .append(" | ")
                    .append(totalEnt)
                    .append(" | ")
                    .append(totalVo)
                    .append(" | ")
                    .append(totalPorts)
                    .append(" | ")
                    .append(formatLoc(totalLoc))
                    .append(" |\n\n");
        }

        // 3.3 Detected Architectural Style
        md.append(numbering.h3("Detected Architectural Style")).append("\n\n");
        appendArchitectureDiagram(md, inventory, style, numbering);

        // 3.4 C4 Model Diagrams (data-driven)
        appendC4Diagrams(md, report, numbering);
    }

    /**
     * Appends C4 model diagrams using data from IrSnapshot and ArchitectureQuery.
     *
     * <p>C4 diagrams provide standardized architectural views:
     * <ul>
     *   <li>System Context - Shows bounded contexts and external actors</li>
     *   <li>Container - Shows driving/driven ports and domain core</li>
     *   <li>Aggregate - Shows aggregate roots with their entities</li>
     *   <li>Port Matrix - Shows port classification (driving vs driven)</li>
     * </ul>
     */
    private void appendC4Diagrams(StringBuilder md, AuditReport report, SectionNumbering numbering) {
        // Only generate if IR snapshot is available
        if (report.model() == null) {
            return;
        }

        md.append(numbering.h3("C4 Model Views")).append("\n\n");

        C4DiagramBuilder c4 = new C4DiagramBuilder();
        String projectName = report.metadata().projectName();

        // System Context Diagram
        md.append(numbering.h4("System Context (C4 Level 1)")).append("\n\n");
        md.append(c4.buildSystemContextDiagram(projectName, report.inventory().boundedContexts()));
        md.append("\n");

        // Container Diagram
        md.append(numbering.h4("Container View (C4 Level 2)")).append("\n\n");
        md.append(c4.buildContainerDiagram(projectName, report.model(), report.architectureQuery()));
        md.append("\n");

        // Aggregate Diagram
        md.append(numbering.h4("Aggregate Model")).append("\n\n");
        md.append(c4.buildAggregateDiagram(report.model()));
        md.append("\n");

        // Port Matrix Diagram
        md.append(numbering.h4("Port Matrix")).append("\n\n");
        md.append(c4.buildPortMatrixDiagram(report.model()));
        md.append("\n");
    }

    /**
     * Formats LOC with thousands separator and tilde for approximation.
     */
    private String formatLoc(int loc) {
        if (loc == 0) {
            return "–";
        }
        return String.format("%,d", loc);
    }

    /**
     * Appends a Mermaid diagram representing the detected architectural style.
     */
    private void appendArchitectureDiagram(
            StringBuilder md,
            ComponentInventory inventory,
            DetectedArchitectureStyle style,
            SectionNumbering numbering) {
        String styleName = getStyleDisplayName(style);
        md.append(numbering.h4(styleName)).append("\n\n");

        switch (style) {
            case HEXAGONAL -> appendHexagonalDiagram(md, inventory);
            case LAYERED -> appendLayeredDiagram(md, inventory);
            case CLEAN -> appendCleanDiagram(md, inventory);
            case ONION -> appendOnionDiagram(md, inventory);
            default -> appendUnknownDiagram(md, inventory);
        }
    }

    private String getStyleDisplayName(DetectedArchitectureStyle style) {
        return switch (style) {
            case HEXAGONAL -> "Hexagonal Architecture (Ports & Adapters)";
            case LAYERED -> "Layered Architecture";
            case CLEAN -> "Clean Architecture";
            case ONION -> "Onion Architecture";
            case UNKNOWN -> "Unknown / Mixed";
        };
    }

    private void appendHexagonalDiagram(StringBuilder md, ComponentInventory inventory) {
        md.append("```mermaid\n");
        md.append("---\n");
        md.append("config:\n");
        md.append("  look: neo\n");
        md.append("  theme: forest\n");
        md.append("title: Hexagonal Architecture (Ports & Adapters)\n");
        md.append("---\n");
        md.append("flowchart LR\n");
        md.append("    subgraph DRIVING[\"DRIVING ADAPTERS\"]\n");
        md.append("        direction TB\n");
        md.append("        DA1[REST API]\n");
        md.append("        DA2[GraphQL]\n");
        md.append("        DA3[CLI]\n\n");
        md.append("        DA1 ~~~ DA2\n");
        md.append("        DA2 ~~~ DA3\n");
        md.append("    end\n\n");

        md.append("    subgraph CORE[\"DOMAIN CORE\"]\n");
        md.append("        direction TB\n");
        md.append("        AGG[\"Aggregates (")
                .append(inventory.aggregateRoots())
                .append(")\"]\n");
        md.append("        ENT[\"Entities (").append(inventory.entities()).append(")\"]\n");
        md.append("        VO[\"Value Objects (")
                .append(inventory.valueObjects())
                .append(")\"]\n");
        md.append("        SVC[\"Domain Services (")
                .append(inventory.domainServices())
                .append(")\"]\n\n");
        md.append("        AGG ~~~ ENT\n");
        md.append("        ENT ~~~ VO\n");
        md.append("        VO ~~~ SVC\n");
        md.append("    end\n\n");

        md.append("    subgraph DRIVEN[\"DRIVEN ADAPTERS\"]\n");
        md.append("        direction TB\n");
        md.append("        DB[(Database)]\n");
        md.append("        MQ[Message Queue]\n");
        md.append("        EXT[External APIs]\n\n");
        md.append("        DB ~~~ MQ\n");
        md.append("        MQ ~~~ EXT\n");
        md.append("    end\n\n");

        md.append("\n");
        md.append("    S1([\"Driving Ports: ")
                .append(inventory.drivingPorts())
                .append("\"]) ~~~ S2([\"Domain Types: ")
                .append(inventory.totalDomainTypes())
                .append("\"])\n");
        md.append("    S2 ~~~ S3([\"Driven Ports: ")
                .append(inventory.drivenPorts())
                .append("\"])\n");
        md.append("\n\n");

        md.append("    DRIVING -->|\"Driving Ports (")
                .append(inventory.drivingPorts())
                .append(")\"| CORE\n");
        md.append("    CORE -->|\"Driven Ports (")
                .append(inventory.drivenPorts())
                .append(")\"| DRIVEN\n");
        md.append("```\n\n");
    }

    private void appendLayeredDiagram(StringBuilder md, ComponentInventory inventory) {
        md.append("```mermaid\n");
        md.append("---\n");
        md.append("config:\n");
        md.append("  look: neo\n");
        md.append("  theme: forest\n");
        md.append("title: Layered Architecture\n");
        md.append("---\n");
        md.append("flowchart TB\n");
        md.append("    subgraph PRESENTATION[\"PRESENTATION LAYER\"]\n");
        md.append("        UI[Controllers / UI]\n");
        md.append("    end\n\n");

        md.append("    subgraph APPLICATION[\"APPLICATION LAYER\"]\n");
        md.append("        SVC[\"Services (").append(inventory.domainServices()).append(")\"]\n");
        md.append("    end\n\n");

        md.append("    subgraph DOMAIN[\"DOMAIN LAYER\"]\n");
        md.append("        direction LR\n");
        md.append("        AGG[\"Aggregates (")
                .append(inventory.aggregateRoots())
                .append(")\"]\n");
        md.append("        ENT[\"Entities (").append(inventory.entities()).append(")\"]\n");
        md.append("        VO[\"Value Objects (")
                .append(inventory.valueObjects())
                .append(")\"]\n\n");
        md.append("        AGG ~~~ ENT\n");
        md.append("        ENT ~~~ VO\n");
        md.append("    end\n\n");

        md.append("    subgraph INFRASTRUCTURE[\"INFRASTRUCTURE LAYER\"]\n");
        md.append("        direction LR\n");
        md.append("        DB[(Database)]\n");
        md.append("        EXT[External Services]\n\n");
        md.append("        DB ~~~ EXT\n");
        md.append("    end\n\n");

        md.append("\n");
        md.append("    S1([\"Driving Ports: ")
                .append(inventory.drivingPorts())
                .append("\"]) ~~~ S2([\"Domain Types: ")
                .append(inventory.totalDomainTypes())
                .append("\"])\n");
        md.append("    S2 ~~~ S3([\"Driven Ports: ")
                .append(inventory.drivenPorts())
                .append("\"])\n");
        md.append("\n\n");

        md.append("    PRESENTATION --> APPLICATION\n");
        md.append("    APPLICATION --> DOMAIN\n");
        md.append("    APPLICATION --> INFRASTRUCTURE\n");
        md.append("```\n\n");
    }

    private void appendCleanDiagram(StringBuilder md, ComponentInventory inventory) {
        md.append("```mermaid\n");
        md.append("---\n");
        md.append("config:\n");
        md.append("  look: neo\n");
        md.append("  theme: forest\n");
        md.append("title: Clean Architecture\n");
        md.append("---\n");
        md.append("flowchart TB\n");
        md.append("    subgraph FRAMEWORKS[\"FRAMEWORKS & DRIVERS\"]\n");
        md.append("        direction LR\n");
        md.append("        WEB[Web / UI]\n");
        md.append("        DB[(Database)]\n\n");
        md.append("        WEB ~~~ DB\n");
        md.append("    end\n\n");

        md.append("    subgraph ADAPTERS[\"INTERFACE ADAPTERS\"]\n");
        md.append("        direction LR\n");
        md.append("        CTRL[Controllers]\n");
        md.append("        GW[Gateways]\n");
        md.append("        PRES[Presenters]\n\n");
        md.append("        CTRL ~~~ GW\n");
        md.append("        GW ~~~ PRES\n");
        md.append("    end\n\n");

        md.append("    subgraph USECASES[\"USE CASES\"]\n");
        md.append("        UC[\"Use Cases (").append(inventory.drivingPorts()).append(")\"]\n");
        md.append("    end\n\n");

        md.append("    subgraph ENTITIES[\"ENTITIES\"]\n");
        md.append("        direction LR\n");
        md.append("        AGG[\"Aggregates (")
                .append(inventory.aggregateRoots())
                .append(")\"]\n");
        md.append("        ENT[\"Entities (").append(inventory.entities()).append(")\"]\n");
        md.append("        VO[\"Value Objects (")
                .append(inventory.valueObjects())
                .append(")\"]\n\n");
        md.append("        AGG ~~~ ENT\n");
        md.append("        ENT ~~~ VO\n");
        md.append("    end\n\n");

        md.append("\n");
        md.append("    S1([\"Driving Ports: ")
                .append(inventory.drivingPorts())
                .append("\"]) ~~~ S2([\"Domain Types: ")
                .append(inventory.totalDomainTypes())
                .append("\"])\n");
        md.append("    S2 ~~~ S3([\"Driven Ports: ")
                .append(inventory.drivenPorts())
                .append("\"])\n");
        md.append("\n\n");

        md.append("    FRAMEWORKS --> ADAPTERS\n");
        md.append("    ADAPTERS --> USECASES\n");
        md.append("    USECASES --> ENTITIES\n");
        md.append("```\n\n");
    }

    private void appendOnionDiagram(StringBuilder md, ComponentInventory inventory) {
        md.append("```mermaid\n");
        md.append("---\n");
        md.append("config:\n");
        md.append("  look: neo\n");
        md.append("  theme: forest\n");
        md.append("title: Onion Architecture\n");
        md.append("---\n");
        md.append("flowchart TB\n");
        md.append("    subgraph INFRA[\"INFRASTRUCTURE\"]\n");
        md.append("        direction LR\n");
        md.append("        UI[UI / API]\n");
        md.append("        DB[(Database)]\n");
        md.append("        EXT[External Services]\n\n");
        md.append("        UI ~~~ DB\n");
        md.append("        DB ~~~ EXT\n");
        md.append("    end\n\n");

        md.append("    subgraph APP[\"APPLICATION SERVICES\"]\n");
        md.append("        SVC[\"Services (").append(inventory.domainServices()).append(")\"]\n");
        md.append("    end\n\n");

        md.append("    subgraph DOMAIN[\"DOMAIN SERVICES\"]\n");
        md.append("        DS[Domain Logic]\n");
        md.append("    end\n\n");

        md.append("    subgraph CORE[\"DOMAIN MODEL\"]\n");
        md.append("        direction LR\n");
        md.append("        AGG[\"Aggregates (")
                .append(inventory.aggregateRoots())
                .append(")\"]\n");
        md.append("        ENT[\"Entities (").append(inventory.entities()).append(")\"]\n");
        md.append("        VO[\"Value Objects (")
                .append(inventory.valueObjects())
                .append(")\"]\n\n");
        md.append("        AGG ~~~ ENT\n");
        md.append("        ENT ~~~ VO\n");
        md.append("    end\n\n");

        md.append("\n");
        md.append("    S1([\"Driving Ports: ")
                .append(inventory.drivingPorts())
                .append("\"]) ~~~ S2([\"Domain Types: ")
                .append(inventory.totalDomainTypes())
                .append("\"])\n");
        md.append("    S2 ~~~ S3([\"Driven Ports: ")
                .append(inventory.drivenPorts())
                .append("\"])\n");
        md.append("\n\n");

        md.append("    INFRA --> APP\n");
        md.append("    APP --> DOMAIN\n");
        md.append("    DOMAIN --> CORE\n");
        md.append("```\n\n");
    }

    private void appendUnknownDiagram(StringBuilder md, ComponentInventory inventory) {
        md.append("```mermaid\n");
        md.append("---\n");
        md.append("config:\n");
        md.append("  look: neo\n");
        md.append("  theme: forest\n");
        md.append("title: Unknown / Mixed\n");
        md.append("---\n");
        md.append("flowchart LR\n");
        md.append("    subgraph COMPONENTS[\"DETECTED COMPONENTS\"]\n");
        md.append("        direction TB\n");
        md.append("        AGG[\"Aggregates (")
                .append(inventory.aggregateRoots())
                .append(")\"]\n");
        md.append("        ENT[\"Entities (").append(inventory.entities()).append(")\"]\n");
        md.append("        VO[\"Value Objects (")
                .append(inventory.valueObjects())
                .append(")\"]\n");
        md.append("        SVC[\"Services (").append(inventory.domainServices()).append(")\"]\n");
        md.append("        PORTS[\"Ports (").append(inventory.totalPorts()).append(")\"]\n\n");
        md.append("        AGG ~~~ ENT\n");
        md.append("        ENT ~~~ VO\n");
        md.append("        VO ~~~ SVC\n");
        md.append("        SVC ~~~ PORTS\n");
        md.append("    end\n\n");

        md.append("\n");
        md.append("    S1([\"Driving Ports: ")
                .append(inventory.drivingPorts())
                .append("\"]) ~~~ S2([\"Domain Types: ")
                .append(inventory.totalDomainTypes())
                .append("\"])\n");
        md.append("    S2 ~~~ S3([\"Driven Ports: ")
                .append(inventory.drivenPorts())
                .append("\"])\n");
        md.append("\n");
        md.append("```\n\n");
        md.append(
                "*Note: The architectural style could not be clearly identified. Consider reviewing package structure and dependencies.*\n\n");
    }

    /**
     * Appends the DDD compliance section with enhanced formatting.
     */
    private void appendDddCompliance(
            StringBuilder md, int dddCompliancePercent, AuditReport report, SectionNumbering numbering) {
        md.append(numbering.h2("Domain-Driven Design Compliance")).append("\n\n");

        // Filter DDD-related violations
        List<ViolationEntry> dddViolations = report.violations().stream()
                .filter(v -> v.constraintId().startsWith("ddd:"))
                .toList();

        // Group violations by constraint ID
        Map<String, List<ViolationEntry>> byConstraint =
                dddViolations.stream().collect(java.util.stream.Collectors.groupingBy(ViolationEntry::constraintId));

        // 4.1 DDD Compliance Score
        md.append(numbering.h3("DDD Compliance Score: " + dddCompliancePercent + "%"))
                .append("\n\n");

        // DDD Rules compliance table
        md.append("| DDD Rule | Compliance | Details |\n");
        md.append("|----------|:----------:|---------|");
        md.append("\n");

        // Calculate rule compliance based on violations and inventory
        var inventory = report.inventory();
        int totalAggregates = inventory.aggregateRoots();
        int totalEntities = inventory.entities() + inventory.aggregateRoots();
        int totalValueObjects = inventory.valueObjects();
        int totalDomainEvents = inventory.domainEvents();

        // Aggregates with identity
        int identityViolations =
                byConstraint.getOrDefault("ddd:entity-identity", List.of()).size();
        int aggregatesWithIdentity = Math.max(0, totalAggregates - identityViolations);
        int identityPercent = totalAggregates > 0 ? (aggregatesWithIdentity * 100 / totalAggregates) : 100;
        md.append("| Aggregates with identity | ")
                .append(identityPercent)
                .append("% | ")
                .append(aggregatesWithIdentity)
                .append("/")
                .append(totalAggregates)
                .append(" aggregates have proper identity |\n");

        // Aggregate boundaries respected
        int boundaryViolations =
                byConstraint.getOrDefault("ddd:aggregate-boundary", List.of()).size();
        int boundaryPercent = totalEntities > 0 ? Math.max(0, 100 - (boundaryViolations * 100 / totalEntities)) : 100;
        String boundaryDetails = boundaryViolations == 0
                ? "All boundaries respected"
                : boundaryViolations + " violation(s): entities accessible outside aggregate";
        md.append("| Aggregate boundaries respected | ")
                .append(boundaryPercent)
                .append("% | ")
                .append(boundaryDetails)
                .append(" |\n");

        // Immutable Value Objects
        int immutabilityViolations = byConstraint
                .getOrDefault("ddd:value-object-immutable", List.of())
                .size();
        int immutableVOs = Math.max(0, totalValueObjects - immutabilityViolations);
        int voPercent = totalValueObjects > 0 ? (immutableVOs * 100 / totalValueObjects) : 100;
        String voDetails = immutabilityViolations == 0
                ? "All VOs are immutable"
                : immutableVOs + "/" + totalValueObjects + " VOs are immutable (" + immutabilityViolations
                        + " with setters)";
        md.append("| Immutable Value Objects | ")
                .append(voPercent)
                .append("% | ")
                .append(voDetails)
                .append(" |\n");

        // One repository per Aggregate Root
        int repoViolations =
                byConstraint.getOrDefault("ddd:aggregate-repository", List.of()).size();
        int repoPercent = totalAggregates > 0 ? Math.max(0, 100 - (repoViolations * 100 / totalAggregates)) : 100;
        String repoDetails = repoViolations == 0
                ? totalAggregates + " repositories for " + totalAggregates + " aggregate roots"
                : repoViolations + " aggregate(s) missing repository";
        md.append("| One repository per Aggregate Root | ")
                .append(repoPercent)
                .append("% | ")
                .append(repoDetails)
                .append(" |\n");

        // No cycles between aggregates
        int cycleViolations =
                byConstraint.getOrDefault("ddd:aggregate-cycle", List.of()).size();
        int cyclePercent = cycleViolations == 0 ? 100 : Math.max(0, 100 - (cycleViolations * 20));
        String cycleDetails = cycleViolations == 0 ? "No cycles detected" : cycleViolations + " cycle(s) detected";
        md.append("| No cycles between aggregates | ")
                .append(cyclePercent)
                .append("% | ")
                .append(cycleDetails)
                .append(" |\n");

        // Domain Events named in past tense
        int eventNamingViolations =
                byConstraint.getOrDefault("ddd:event-naming", List.of()).size();
        int correctEvents = Math.max(0, totalDomainEvents - eventNamingViolations);
        int eventPercent = totalDomainEvents > 0 ? (correctEvents * 100 / totalDomainEvents) : 100;
        String eventDetails = eventNamingViolations == 0
                ? "All events correctly named"
                : correctEvents + "/" + totalDomainEvents + " events correctly named";
        md.append("| Domain Events named in past tense | ")
                .append(eventPercent)
                .append("% | ")
                .append(eventDetails)
                .append(" |\n");

        // Domain purity
        int purityViolations =
                byConstraint.getOrDefault("ddd:domain-purity", List.of()).size();
        int purityPercent = purityViolations == 0 ? 100 : Math.max(0, 100 - (purityViolations * 10));
        String purityDetails = purityViolations == 0
                ? "Domain layer is pure"
                : purityViolations + " domain type(s) with forbidden imports";
        md.append("| Domain purity (no infrastructure) | ")
                .append(purityPercent)
                .append("% | ")
                .append(purityDetails)
                .append(" |\n\n");

        // 4.2 Aggregate Analysis
        if (!report.aggregateDetails().isEmpty()) {
            md.append(numbering.h3("Aggregate Analysis")).append("\n\n");

            md.append("| Aggregate Root | Entities | VOs | Repository | Cohesion | Status |\n");
            md.append("|----------------|:--------:|:---:|:----------:|:--------:|:------:|\n");

            for (var agg : report.aggregateDetails()) {
                String repoStatus = agg.hasRepository() ? "✅" : "❌";
                String cohesionStr = agg.cohesion() >= 0 ? String.format("%.2f", agg.cohesion()) : "–";
                String status =
                        switch (agg.status()) {
                            case OK -> "✅";
                            case WARNING -> "⚠️";
                            case PROBLEM -> "❌";
                        };

                md.append("| `")
                        .append(agg.rootName())
                        .append("` | ")
                        .append(agg.entityCount())
                        .append(" | ")
                        .append(agg.valueObjectCount())
                        .append(" | ")
                        .append(repoStatus)
                        .append(" | ")
                        .append(cohesionStr)
                        .append(" | ")
                        .append(status)
                        .append(" |\n");
            }
            md.append("\n");
        } else if (!inventory.aggregateExamples().isEmpty()) {
            // Fallback to old display if aggregateDetails not available
            md.append(numbering.h3("Aggregate Analysis")).append("\n\n");

            md.append("| Aggregate Root | Repository | Status |\n");
            md.append("|----------------|:----------:|:------:|\n");

            for (String agg : inventory.aggregateExamples()) {
                boolean hasRepoViolation = byConstraint.getOrDefault("ddd:aggregate-repository", List.of()).stream()
                        .anyMatch(v ->
                                v.message().contains(agg) || v.affectedType().contains(agg));
                String repoStatus = hasRepoViolation ? "❌" : "✅";

                boolean hasCycle = byConstraint.getOrDefault("ddd:aggregate-cycle", List.of()).stream()
                        .anyMatch(v -> v.message().contains(agg));
                String status = hasCycle ? "⚠️" : "✅";

                md.append("| `")
                        .append(agg)
                        .append("` | ")
                        .append(repoStatus)
                        .append(" | ")
                        .append(status)
                        .append(" |\n");
            }

            if (inventory.aggregateRoots() > inventory.aggregateExamples().size()) {
                md.append("| *... and ")
                        .append(inventory.aggregateRoots()
                                - inventory.aggregateExamples().size())
                        .append(" more* | | |\n");
            }
            md.append("\n");

            // Show Bounded Context breakdown as a separate sub-section
            if (!inventory.boundedContexts().isEmpty()) {
                md.append("**Bounded Context Distribution:**\n\n");
                md.append("| Bounded Context | Aggregates | Entities | VOs | Ports |\n");
                md.append("|-----------------|:----------:|:--------:|:---:|:-----:|\n");
                for (var bc : inventory.boundedContexts()) {
                    md.append("| ")
                            .append(bc.name())
                            .append(" | ")
                            .append(bc.aggregates())
                            .append(" | ")
                            .append(bc.entities())
                            .append(" | ")
                            .append(bc.valueObjects())
                            .append(" | ")
                            .append(bc.ports())
                            .append(" |\n");
                }
                md.append("\n");
            }
        }

        // 4.3 Detected DDD Violations
        if (!dddViolations.isEmpty()) {
            md.append(numbering.h3("Detected DDD Violations")).append("\n\n");

            // Aggregate Cycles - with ASCII diagram
            var cycleViolationsList = byConstraint.getOrDefault("ddd:aggregate-cycle", List.of());
            if (!cycleViolationsList.isEmpty()) {
                md.append("#### CRITICAL: Aggregate Dependency Cycles\n\n");

                for (var violation : cycleViolationsList) {
                    // Extract cycle information from message
                    String message = violation.message();
                    String cycleInfo = message.contains(":")
                            ? message.substring(message.lastIndexOf(":") + 1).trim()
                            : message;

                    md.append("```\n");
                    md.append("┌─────────────────────────────────────────────────────────────┐\n");
                    md.append("│                    CYCLE DETECTED                           │\n");
                    md.append("│                                                             │\n");
                    md.append("│  ").append(String.format("%-58s", cycleInfo)).append(" │\n");
                    md.append("│                                                             │\n");
                    md.append("│  Impact: Aggregates are coupled, violating DDD boundaries   │\n");
                    md.append("│  Risk: Potential cascade updates and transactional issues   │\n");
                    md.append("│                                                             │\n");
                    md.append("│  Recommendation: Use Domain Events to decouple              │\n");
                    md.append("└─────────────────────────────────────────────────────────────┘\n");
                    md.append("```\n\n");
                }
            }

            // Domain Purity Violations
            var purityViolationsList = byConstraint.getOrDefault("ddd:domain-purity", List.of());
            if (!purityViolationsList.isEmpty()) {
                md.append("#### MAJOR: Domain Purity Violations\n\n");
                md.append("| Domain Type | Issue | Location |\n");
                md.append("|-------------|-------|----------|\n");
                for (var violation : purityViolationsList) {
                    md.append("| `")
                            .append(violation.affectedType())
                            .append("` | ")
                            .append(escapeMarkdown(violation.message()))
                            .append(" | `")
                            .append(violation.location())
                            .append("` |\n");
                }
                md.append("\n");
            }

            // Event Naming Violations
            var eventViolationsList = byConstraint.getOrDefault("ddd:event-naming", List.of());
            if (!eventViolationsList.isEmpty()) {
                md.append("#### MINOR: Event Naming Violations\n\n");
                md.append("| Event | Issue | Suggestion |\n");
                md.append("|-------|-------|------------|\n");
                for (var violation : eventViolationsList) {
                    String eventName = extractSimpleName(violation.location());
                    String suggestion = eventName
                            .replace("Event", "edEvent")
                            .replace("PlaceEvent", "PlacedEvent")
                            .replace("CancelEvent", "CancelledEvent")
                            .replace("AddEvent", "AddedEvent");
                    md.append("| `")
                            .append(eventName)
                            .append("` | ")
                            .append("Should be named in past tense | `")
                            .append(suggestion)
                            .append("` |\n");
                }
                md.append("\n");
            }

            // Other DDD violations
            var otherViolations = dddViolations.stream()
                    .filter(v -> !v.constraintId().equals("ddd:aggregate-cycle")
                            && !v.constraintId().equals("ddd:domain-purity")
                            && !v.constraintId().equals("ddd:event-naming"))
                    .toList();

            if (!otherViolations.isEmpty()) {
                md.append("#### Other DDD Violations\n\n");
                md.append("| Constraint | Affected Type | Message |\n");
                md.append("|------------|---------------|---------|");
                md.append("\n");
                for (var violation : otherViolations) {
                    md.append("| `")
                            .append(violation.constraintId())
                            .append("` | `")
                            .append(violation.affectedType())
                            .append("` | ")
                            .append(escapeMarkdown(violation.message()))
                            .append(" |\n");
                }
                md.append("\n");
            }
        } else {
            md.append(
                    "✅ **No DDD violations detected.** The domain model follows DDD tactical patterns correctly.\n\n");
        }
    }

    /**
     * Extracts the simple class name from a location string like "com.example.Order:1:1".
     */
    private String extractSimpleName(String location) {
        if (location == null || location.isEmpty()) {
            return "Unknown";
        }
        String qualifiedName = location.contains(":") ? location.substring(0, location.indexOf(':')) : location;
        int lastDot = qualifiedName.lastIndexOf('.');
        return lastDot >= 0 ? qualifiedName.substring(lastDot + 1) : qualifiedName;
    }

    /**
     * Appends the hexagonal compliance section with port matrix.
     */
    private void appendHexagonalCompliance(
            StringBuilder md,
            int hexCompliancePercent,
            java.util.List<PortMatrixEntry> portMatrix,
            SectionNumbering numbering) {
        md.append(numbering.h2("Hexagonal Compliance")).append("\n\n");
        md.append("**Score: ").append(hexCompliancePercent).append("%**\n\n");

        // Port Matrix
        if (!portMatrix.isEmpty()) {
            md.append(numbering.h3("Port Matrix")).append("\n\n");
            md.append("| Port | Direction | Kind | Managed Type | Methods | Adapter |\n");
            md.append("|------|-----------|------|--------------|---------|--------|\n");
            for (var port : portMatrix) {
                String adapterDisplay = switch (port.adapterStatus()) {
                    case PortMatrixEntry.ADAPTER_DETECTED -> "✅";
                    case PortMatrixEntry.ADAPTER_NOT_DETECTED -> "⚠️ Not detected";
                    default -> "❓ Unknown";
                };
                md.append("| `")
                        .append(port.portName())
                        .append("` | ")
                        .append(port.direction())
                        .append(" | ")
                        .append(port.kind())
                        .append(" | ")
                        .append(port.managedType() != null ? "`" + port.managedType() + "`" : "-")
                        .append(" | ")
                        .append(port.methodCount())
                        .append(" | ")
                        .append(adapterDisplay)
                        .append(" |\n");
            }
            md.append("\n");
        }
    }

    /**
     * Appends the technical debt section.
     */
    private void appendTechnicalDebt(StringBuilder md, TechnicalDebtSummary debt, SectionNumbering numbering) {
        md.append(numbering.h2("Technical Debt")).append("\n\n");

        if (debt.isZero()) {
            md.append("✅ **No technical debt detected.**\n\n");
            return;
        }

        // Summary
        md.append("| Metric | Value |\n");
        md.append("|--------|-------|\n");
        md.append("| Total Effort | **")
                .append(String.format("%.1f", debt.totalDays()))
                .append(" person-days** |\n");
        md.append("| Total Cost | **")
                .append(String.format("%.2f €", debt.totalCost()))
                .append("** |\n");
        md.append("| Monthly Interest | ")
                .append(String.format("%.2f €", debt.monthlyInterest()))
                .append(" |\n\n");

        // Breakdown by category
        if (!debt.breakdown().isEmpty()) {
            md.append(numbering.h3("Breakdown by Category")).append("\n\n");
            md.append("| Category | Days | Cost | Description |\n");
            md.append("|----------|------|------|-------------|\n");
            for (var cat : debt.breakdown()) {
                md.append("| ")
                        .append(cat.category())
                        .append(" | ")
                        .append(String.format("%.1f", cat.days()))
                        .append(" | ")
                        .append(String.format("%.2f €", cat.cost()))
                        .append(" | ")
                        .append(escapeMarkdown(cat.description()))
                        .append(" |\n");
            }
            md.append("\n");
        }
    }

    /**
     * Appends the recommendations section.
     */
    private void appendRecommendations(
            StringBuilder md, java.util.List<Recommendation> recommendations, SectionNumbering numbering) {
        md.append(numbering.h2("Recommendations")).append("\n\n");

        if (recommendations.isEmpty()) {
            md.append("✅ **No specific recommendations - the architecture is in good shape!**\n\n");
            return;
        }

        md.append("| Priority | Title | Effort | Impact |\n");
        md.append("|----------|-------|--------|--------|\n");
        for (var rec : recommendations) {
            String priorityEmoji = getPriorityEmoji(rec.priority().name());
            md.append("| ")
                    .append(priorityEmoji)
                    .append(" ")
                    .append(rec.priority())
                    .append(" | ")
                    .append(escapeMarkdown(rec.title()))
                    .append(" | ")
                    .append(String.format("%.1f days", rec.estimatedEffort()))
                    .append(" | ")
                    .append(escapeMarkdown(rec.expectedImpact()))
                    .append(" |\n");
        }
        md.append("\n");

        // Details
        md.append("<details>\n");
        md.append("<summary><strong>Recommendation Details</strong></summary>\n\n");
        for (var rec : recommendations) {
            md.append("### ").append(rec.title()).append("\n\n");
            md.append("**Priority:** ").append(rec.priority()).append("  \n");
            md.append("**Estimated Effort:** ")
                    .append(String.format("%.1f days", rec.estimatedEffort()))
                    .append("  \n");
            md.append("**Expected Impact:** ").append(rec.expectedImpact()).append("\n\n");
            md.append(rec.description()).append("\n\n");
            if (!rec.affectedTypes().isEmpty()) {
                md.append("**Affected Types:**\n");
                for (String type : rec.affectedTypes()) {
                    md.append("- `").append(type).append("`\n");
                }
                md.append("\n");
            }
        }
        md.append("</details>\n\n");
    }

    /**
     * Returns an emoji for the recommendation priority.
     */
    private String getPriorityEmoji(String priority) {
        return switch (priority.toUpperCase()) {
            case "IMMEDIATE" -> "🔴";
            case "SHORT_TERM" -> "🟠";
            case "MEDIUM_TERM" -> "🟡";
            case "LOW" -> "🟢";
            default -> "⚪";
        };
    }

    /**
     * Extracts a category and observation from a strength description.
     *
     * <p>Parses strength strings to extract meaningful categories like
     * "Domain Model", "Architecture", "Ports", "Cohesion", etc.
     *
     * @param strength the strength description
     * @return array with [category, observation]
     */
    private String[] extractCategoryAndObservation(String strength) {
        String lowerStrength = strength.toLowerCase();

        // DDD patterns
        if (lowerStrength.contains("ddd") || lowerStrength.contains("domain-driven")) {
            return new String[] {"DDD Patterns", strength};
        }
        if (lowerStrength.contains("domain model") || lowerStrength.contains("value object")) {
            return new String[] {"Domain Model", strength};
        }
        if (lowerStrength.contains("aggregate")) {
            return new String[] {"Aggregates", strength};
        }

        // Hexagonal architecture
        if (lowerStrength.contains("hexagonal")) {
            return new String[] {"Hexagonal Architecture", strength};
        }
        if (lowerStrength.contains("port")) {
            return new String[] {"Ports", strength};
        }

        // Architecture quality
        if (lowerStrength.contains("cycle") || lowerStrength.contains("layer violation")) {
            return new String[] {"Architecture", strength};
        }
        if (lowerStrength.contains("cohesion")) {
            return new String[] {"Cohesion", strength};
        }
        if (lowerStrength.contains("coupling")) {
            return new String[] {"Coupling", strength};
        }
        if (lowerStrength.contains("dependency")) {
            return new String[] {"Dependencies", strength};
        }

        // Default
        return new String[] {"General", strength};
    }
}
