/*
 * This Source Code Form is part of the HexaGlue project.
 * Copyright (c) 2026 Scalastic
 *
 * This Source Code Form is subject to the terms of the Mozilla Public
 * License, v. 2.0. If a copy of the MPL was not distributed with this
 * file, You can obtain one at https://mozilla.org/MPL/2.0/.
 *
 * Commercial licensing options are available for organizations wishing
 * to use HexaGlue under terms different from the MPL 2.0.
 * Contact: info@hexaglue.io
 */

package io.hexaglue.plugin.livingdoc.util;

import java.util.Optional;

/**
 * Provides version information for the Living Documentation Plugin.
 *
 * <p>Reads the version from the JAR's MANIFEST.MF, which is set
 * by maven-jar-plugin with addDefaultImplementationEntries=true.
 *
 * @since 2.0.0
 */
public final class PluginVersion {

    private static final String VERSION = Optional.ofNullable(
                    PluginVersion.class.getPackage().getImplementationVersion())
            .orElse("dev");

    private PluginVersion() {
        // Utility class
    }

    /**
     * Returns the plugin version.
     *
     * @return the version string (e.g., "2.0.0-SNAPSHOT" or "dev" in IDE)
     */
    public static String get() {
        return VERSION;
    }

    /**
     * Returns the formatted generator header for documentation.
     *
     * @return the formatted header (e.g., "Generated by HexaGlue Living Documentation Plugin v2.0.0-SNAPSHOT")
     */
    public static String generatorHeader() {
        return "*Generated by HexaGlue Living Documentation Plugin v" + VERSION + "*";
    }
}
