# HexaGlue Classification Profile - Default
#
# This profile documents the default priorities used by HexaGlue classification.
# No overrides are applied - this file serves as documentation and a template
# for creating custom profiles.
#
# Priority levels:
#   100 = Explicit (annotations, interfaces)
#   85  = Semantic criteria (structural analysis)
#   80  = Strong heuristics
#   75  = CQRS patterns, relationships
#   72  = Saga detection
#   70  = Signature-based, embedding
#   65  = Port dependencies
#   60  = Medium heuristics, package-based
#   55  = Naming heuristics
#   50  = Lower heuristics
#   40  = Model classification
#
# Criteria keys use the stable ID format: {target}.{category}.{name}
#
# Usage:
#   CriteriaProfile profile = YamlCriteriaProfile.fromResource("profiles/default.yaml");
#   DomainClassifier classifier = new DomainClassifier(DomainClassifier.defaultCriteria(), profile);

priorities:
  # =====================================================================
  # DOMAIN CLASSIFICATION CRITERIA
  # =====================================================================

  # Explicit annotations (priority 100)
  # These always win when present
  domain.explicit.aggregateRoot: 100
  domain.explicit.entity: 100
  domain.explicit.valueObject: 100
  domain.explicit.identifier: 100
  domain.explicit.domainEvent: 100
  domain.explicit.jmoleculesInterface: 100

  # Strong heuristics (priority 80)
  domain.structural.repositoryDominant: 80
  domain.structural.recordSingleId: 80

  # Inherited classification (priority 75)
  domain.structural.inheritedClassification: 75

  # Semantic criteria for flexible domain classification (priority 72)
  domain.semantic.saga: 72
  domain.semantic.outboundOnly: 70
  domain.semantic.inboundOnly: 70

  # Medium heuristics (priority 70)
  domain.structural.embeddedValueObject: 70

  # Relationship-based (priority 65)
  domain.structural.hasPortDependencies: 65

  # Medium heuristics (priority 60)
  domain.structural.hasIdentity: 60
  domain.structural.collectionElementEntity: 60
  domain.structural.immutableNoId: 60

  # Naming heuristics (priority 55)
  domain.naming.domainEvent: 55
  domain.structural.statelessNoDependencies: 55

  # Lower heuristics (priority 50)
  domain.structural.unreferencedInPorts: 50

  # =====================================================================
  # PORT CLASSIFICATION CRITERIA
  # =====================================================================

  # Explicit annotations (priority 100)
  port.explicit.repository: 100
  port.explicit.primaryPort: 100
  port.explicit.secondaryPort: 100
  port.explicit.useCase: 100
  port.explicit.gateway: 100

  # Semantic criteria (priority 85)
  port.semantic.driving: 85
  port.semantic.driven: 85

  # Strong naming heuristics (priority 80)
  port.naming.repository: 80
  port.naming.useCase: 80
  port.naming.gateway: 80

  # CQRS patterns (priority 75)
  port.pattern.command: 75
  port.pattern.query: 75
  port.relationship.injectedAsDependency: 75

  # Signature-based (priority 70)
  port.signature.drivenPort: 70

  # Package-based (priority 60)
  port.package.in: 60
  port.package.out: 60
