/*
 * This Source Code Form is part of the HexaGlue project.
 * Copyright (c) 2026 Scalastic
 *
 * This Source Code Form is subject to the terms of the Mozilla Public
 * License, v. 2.0. If a copy of the MPL was not distributed with this
 * file, You can obtain one at https://mozilla.org/MPL/2.0/.
 *
 * Commercial licensing options are available for organizations wishing
 * to use HexaGlue under terms different from the MPL 2.0.
 * Contact: info@hexaglue.io
 */

package io.hexaglue.plugin.livingdoc.generator;

import io.hexaglue.plugin.livingdoc.content.DomainContentSelector;
import io.hexaglue.plugin.livingdoc.content.PortContentSelector;
import io.hexaglue.plugin.livingdoc.markdown.MarkdownBuilder;
import io.hexaglue.plugin.livingdoc.model.DomainTypeDoc;
import io.hexaglue.plugin.livingdoc.model.PortDoc;
import io.hexaglue.plugin.livingdoc.renderer.DiagramRenderer;
import io.hexaglue.spi.ir.IrSnapshot;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * Generates Mermaid diagrams for the architecture.
 *
 * <p>Uses three-layer architecture:
 * <ol>
 *   <li>ContentSelector - selects and transforms IR data to documentation models</li>
 *   <li>DocumentationModel - immutable records representing documentation content</li>
 *   <li>Renderer - renders documentation models to Mermaid diagrams</li>
 * </ol>
 */
public final class DiagramGenerator {

    private final DomainContentSelector domainSelector;
    private final PortContentSelector portSelector;
    private final DiagramRenderer renderer;

    public DiagramGenerator(IrSnapshot ir) {
        this.domainSelector = new DomainContentSelector(ir);
        this.portSelector = new PortContentSelector(ir);
        this.renderer = new DiagramRenderer();
    }

    public String generate() {
        MarkdownBuilder md = new MarkdownBuilder()
                .h1("Architecture Diagrams")
                .paragraph("*Generated by HexaGlue Living Documentation Plugin*")
                .link("Back to Overview", "README.md")
                .newline()
                .newline()
                .horizontalRule();

        // Domain Model Class Diagram
        generateDomainClassDiagram(md);

        // Aggregate Diagrams
        generateAggregateDiagrams(md);

        // Ports Flow Diagram
        generatePortsFlowDiagram(md);

        // Dependencies Diagram
        generateDependenciesDiagram(md);

        return md.build();
    }

    private void generateDomainClassDiagram(MarkdownBuilder md) {
        md.h2("Domain Model").paragraph("Class diagram showing domain types.");

        List<DomainTypeDoc> allTypes = domainSelector.selectAllTypes();
        md.raw(renderer.renderDomainClassDiagram(allTypes));
    }

    private void generateAggregateDiagrams(MarkdownBuilder md) {
        List<DomainTypeDoc> aggregates = domainSelector.selectAggregateRoots();
        if (aggregates.isEmpty()) {
            return;
        }

        md.h2("Aggregates").paragraph("Each aggregate root with its entities and value objects.");

        // Build a map of all types for lookups
        List<DomainTypeDoc> allTypes = domainSelector.selectAllTypes();
        Map<String, DomainTypeDoc> typeMap = new HashMap<>();
        for (DomainTypeDoc type : allTypes) {
            typeMap.put(type.debug().qualifiedName(), type);
        }

        for (DomainTypeDoc aggregate : aggregates) {
            md.h3(aggregate.name() + " Aggregate").raw(renderer.renderAggregateDiagram(aggregate, typeMap));
        }
    }

    private void generatePortsFlowDiagram(MarkdownBuilder md) {
        md.h2("Port Interactions").paragraph("Flow of interactions through the hexagonal architecture.");

        List<PortDoc> drivingPorts = portSelector.selectDrivingPorts();
        List<PortDoc> drivenPorts = portSelector.selectDrivenPorts();
        List<DomainTypeDoc> aggregates = domainSelector.selectAggregateRoots();

        md.raw(renderer.renderPortsFlowDiagram(drivingPorts, drivenPorts, aggregates));
    }

    private void generateDependenciesDiagram(MarkdownBuilder md) {
        md.h2("Dependencies").paragraph("Code dependencies in hexagonal architecture point toward the domain.");

        List<PortDoc> drivingPorts = portSelector.selectDrivingPorts();
        List<PortDoc> drivenPorts = portSelector.selectDrivenPorts();
        List<DomainTypeDoc> aggregates = domainSelector.selectAggregateRoots();

        md.raw(renderer.renderDependenciesDiagram(drivingPorts, drivenPorts, aggregates));
    }
}
