/*
 * This Source Code Form is part of the HexaGlue project.
 * Copyright (c) 2026 Scalastic
 *
 * This Source Code Form is subject to the terms of the Mozilla Public
 * License, v. 2.0. If a copy of the MPL was not distributed with this
 * file, You can obtain one at https://mozilla.org/MPL/2.0/.
 *
 * Commercial licensing options are available for organizations wishing
 * to use HexaGlue under terms different from the MPL 2.0.
 * Contact: info@hexaglue.io
 */

package io.hexaglue.plugin.rest.model;

import java.util.List;
import java.util.Objects;

/**
 * Specification for the Spring {@code @Configuration} class generated by the REST plugin.
 *
 * <p>The configuration class exposes application services as Spring beans via
 * their driving port interfaces, enabling constructor injection in generated controllers.
 *
 * @param className   the configuration class name (e.g., "RestConfiguration")
 * @param packageName the target package (e.g., "com.acme.api.config")
 * @param beans       the application service bean specifications
 * @since 3.1.0
 */
public record RestConfigurationSpec(String className, String packageName, List<ApplicationServiceBeanSpec> beans) {

    /**
     * Creates a new RestConfigurationSpec with defensive copy.
     *
     * @param className   the class name, must not be null or blank
     * @param packageName the package name, must not be null or blank
     * @param beans       the bean specifications, must not be null
     * @throws NullPointerException     if any argument is null
     * @throws IllegalArgumentException if className or packageName is blank
     */
    public RestConfigurationSpec {
        Objects.requireNonNull(className, "className must not be null");
        Objects.requireNonNull(packageName, "packageName must not be null");
        Objects.requireNonNull(beans, "beans must not be null");
        if (className.isBlank()) {
            throw new IllegalArgumentException("className must not be blank");
        }
        if (packageName.isBlank()) {
            throw new IllegalArgumentException("packageName must not be blank");
        }
        beans = List.copyOf(beans);
    }
}
