/*
 * This Source Code Form is part of the HexaGlue project.
 * Copyright (c) 2026 Scalastic
 *
 * This Source Code Form is subject to the terms of the Mozilla Public
 * License, v. 2.0. If a copy of the MPL was not distributed with this
 * file, You can obtain one at https://mozilla.org/MPL/2.0/.
 *
 * Commercial licensing options are available for organizations wishing
 * to use HexaGlue under terms different from the MPL 2.0.
 * Contact: info@hexaglue.io
 */

package io.hexaglue.plugin.jpa;

import io.hexaglue.spi.ir.DomainType;
import io.hexaglue.spi.ir.Identity;
import java.util.HashSet;
import java.util.Set;

/**
 * Generates Spring Data JPA repository interfaces from domain types.
 */
final class JpaRepositoryGenerator {

    private final String infrastructurePackage;
    private final JpaConfig config;

    JpaRepositoryGenerator(String infrastructurePackage, JpaConfig config) {
        this.infrastructurePackage = infrastructurePackage;
        this.config = config;
    }

    /**
     * Generates a Spring Data JPA repository interface for a domain entity.
     */
    String generateRepository(DomainType domainType) {
        String entityName = domainType.simpleName() + config.entitySuffix();
        String repositoryName = domainType.simpleName() + config.repositorySuffix();
        StringBuilder sb = new StringBuilder();
        Set<String> imports = new HashSet<>();

        // Collect imports
        imports.add("javax.annotation.processing.Generated");
        imports.add("org.springframework.data.jpa.repository.JpaRepository");
        imports.add("org.springframework.stereotype.Repository");

        String idType = "Long"; // default
        if (domainType.hasIdentity()) {
            Identity id = domainType.identity().get();
            idType = mapToJpaType(id.unwrappedType().qualifiedName());
            collectIdImports(imports, id);
        }

        // Package
        sb.append("package ").append(infrastructurePackage).append(";\n\n");

        // Imports
        imports.stream()
                .sorted()
                .forEach(imp -> sb.append("import ").append(imp).append(";\n"));
        sb.append("\n");

        // Interface javadoc
        sb.append("/**\n");
        sb.append(" * Spring Data JPA repository for {@link ")
                .append(entityName)
                .append("}.\n");
        sb.append(" *\n");
        sb.append(" * <p>Provides standard CRUD operations and query methods.\n");
        sb.append(" *\n");
        sb.append(" * <p>Generated by HexaGlue JPA Plugin.\n");
        sb.append(" */\n");

        // Annotations
        sb.append("@Generated(value = \"io.hexaglue.plugin.jpa\")\n");
        sb.append("@Repository\n");

        // Interface declaration
        sb.append("public interface ")
                .append(repositoryName)
                .append(" extends JpaRepository<")
                .append(entityName)
                .append(", ")
                .append(idType)
                .append("> {\n\n");

        // Optional: add custom query methods based on entity properties
        generateQueryMethods(sb, domainType);

        sb.append("}\n");

        return sb.toString();
    }

    private void collectIdImports(Set<String> imports, Identity id) {
        String typeName = id.unwrappedType().qualifiedName();
        if (typeName.equals("java.util.UUID")) {
            imports.add("java.util.UUID");
        }
    }

    private void generateQueryMethods(StringBuilder sb, DomainType domainType) {
        // Generate findBy methods for common patterns
        domainType.properties().stream()
                .filter(prop -> !prop.isIdentity())
                .filter(prop -> isQueryableType(prop.type().unwrapElement().qualifiedName()))
                .limit(3) // Limit to avoid too many methods
                .forEach(prop -> {
                    String propName = prop.name();
                    String capName = capitalize(propName);
                    String propType = mapToJavaType(prop.type().unwrapElement().qualifiedName());

                    sb.append("    /**\n");
                    sb.append("     * Finds entities by ").append(propName).append(".\n");
                    sb.append("     *\n");
                    sb.append("     * @param ")
                            .append(propName)
                            .append(" the ")
                            .append(propName)
                            .append(" to search for\n");
                    sb.append("     * @return list of matching entities\n");
                    sb.append("     */\n");
                    sb.append("    java.util.List<")
                            .append(domainType.simpleName())
                            .append(config.entitySuffix())
                            .append("> findBy")
                            .append(capName)
                            .append("(")
                            .append(propType)
                            .append(" ")
                            .append(propName)
                            .append(");\n\n");
                });
    }

    private boolean isQueryableType(String typeName) {
        return switch (typeName) {
            case "java.lang.String",
                    "String",
                    "java.lang.Long",
                    "Long",
                    "long",
                    "java.lang.Integer",
                    "Integer",
                    "int",
                    "java.util.UUID",
                    "UUID",
                    "java.time.LocalDate",
                    "LocalDate" -> true;
            default -> false;
        };
    }

    private String mapToJpaType(String domainType) {
        return switch (domainType) {
            case "java.util.UUID", "UUID" -> "UUID";
            case "java.lang.String", "String" -> "String";
            case "java.lang.Long", "Long", "long" -> "Long";
            case "java.lang.Integer", "Integer", "int" -> "Integer";
            default -> {
                int lastDot = domainType.lastIndexOf('.');
                yield lastDot >= 0 ? domainType.substring(lastDot + 1) : domainType;
            }
        };
    }

    private String mapToJavaType(String typeName) {
        return switch (typeName) {
            case "java.util.UUID" -> "java.util.UUID";
            case "java.lang.String", "String" -> "String";
            case "java.lang.Long", "Long", "long" -> "Long";
            case "java.lang.Integer", "Integer", "int" -> "Integer";
            case "java.time.LocalDate", "LocalDate" -> "java.time.LocalDate";
            default -> typeName;
        };
    }

    private String capitalize(String str) {
        if (str == null || str.isEmpty()) {
            return str;
        }
        return Character.toUpperCase(str.charAt(0)) + str.substring(1);
    }
}
