package io.hexaglue.plugin.livingdoc;

import io.hexaglue.spi.ir.DomainKind;
import io.hexaglue.spi.ir.DomainType;
import io.hexaglue.spi.ir.IrSnapshot;
import io.hexaglue.spi.ir.Port;
import java.util.List;

/**
 * Generates the architecture overview documentation.
 */
final class OverviewGenerator {

    private final IrSnapshot ir;

    OverviewGenerator(IrSnapshot ir) {
        this.ir = ir;
    }

    String generate(boolean includeDiagram) {
        StringBuilder sb = new StringBuilder();

        // Title
        sb.append("# Architecture Overview\n\n");
        sb.append("*Generated by HexaGlue Living Documentation Plugin*\n\n");
        sb.append("---\n\n");

        // Summary
        generateSummary(sb);

        // Quick links
        sb.append("## Documentation\n\n");
        sb.append("- [Domain Model](domain.md) - Aggregates, entities, and value objects\n");
        sb.append("- [Ports](ports.md) - Driving and driven ports\n");
        if (includeDiagram) {
            sb.append("- [Diagrams](diagrams.md) - Architecture diagrams\n");
        }
        sb.append("\n---\n\n");

        // Architecture overview diagram
        if (includeDiagram) {
            generateOverviewDiagram(sb);
        }

        // Domain summary
        generateDomainSummary(sb);

        // Ports summary
        generatePortsSummary(sb);

        return sb.toString();
    }

    private void generateSummary(StringBuilder sb) {
        sb.append("## Summary\n\n");
        sb.append("| Metric | Count |\n");
        sb.append("|--------|-------|\n");
        sb.append("| Aggregate Roots | ")
                .append(ir.domain().aggregateRoots().size())
                .append(" |\n");
        sb.append("| Entities | ")
                .append(ir.domain().typesOfKind(DomainKind.ENTITY).size())
                .append(" |\n");
        sb.append("| Value Objects | ")
                .append(ir.domain().valueObjects().size())
                .append(" |\n");
        sb.append("| Driving Ports | ").append(ir.ports().drivingPorts().size()).append(" |\n");
        sb.append("| Driven Ports | ").append(ir.ports().drivenPorts().size()).append(" |\n");
        sb.append("\n");
    }

    private void generateOverviewDiagram(StringBuilder sb) {
        sb.append("## Architecture Diagram\n\n");
        sb.append("```mermaid\n");
        sb.append("graph LR\n");
        sb.append("    subgraph External[\"External Actors\"]\n");
        sb.append("        UI[UI/API]\n");
        sb.append("    end\n\n");

        sb.append("    subgraph Application[\"Application\"]\n");
        sb.append("        subgraph DrivingPorts[\"Driving Ports\"]\n");
        List<Port> driving = ir.ports().drivingPorts();
        if (driving.isEmpty()) {
            sb.append("            DP[\"(none)\"]\n");
        } else {
            for (Port port : driving) {
                sb.append("            ")
                        .append(sanitizeId(port.simpleName()))
                        .append("[\"")
                        .append(port.simpleName())
                        .append("\"]\n");
            }
        }
        sb.append("        end\n\n");

        sb.append("        subgraph Domain[\"Domain\"]\n");
        List<DomainType> aggregates = ir.domain().aggregateRoots();
        if (aggregates.isEmpty()) {
            sb.append("            D[\"(domain)\"]\n");
        } else {
            for (DomainType agg : aggregates) {
                sb.append("            ")
                        .append(sanitizeId(agg.simpleName()))
                        .append("[\"")
                        .append(agg.simpleName())
                        .append("\"]\n");
            }
        }
        sb.append("        end\n\n");

        sb.append("        subgraph DrivenPorts[\"Driven Ports\"]\n");
        List<Port> driven = ir.ports().drivenPorts();
        if (driven.isEmpty()) {
            sb.append("            DPOUT[\"(none)\"]\n");
        } else {
            for (Port port : driven) {
                sb.append("            ")
                        .append(sanitizeId(port.simpleName()))
                        .append("[\"")
                        .append(port.simpleName())
                        .append("\"]\n");
            }
        }
        sb.append("        end\n");
        sb.append("    end\n\n");

        sb.append("    subgraph Infrastructure[\"Infrastructure\"]\n");
        sb.append("        DB[(Database)]\n");
        sb.append("        EXT[External Services]\n");
        sb.append("    end\n\n");

        // Connections
        sb.append("    UI --> DrivingPorts\n");
        sb.append("    DrivingPorts --> Domain\n");
        sb.append("    Domain --> DrivenPorts\n");
        sb.append("    DrivenPorts --> DB\n");
        sb.append("    DrivenPorts --> EXT\n");

        sb.append("```\n\n");
    }

    private void generateDomainSummary(StringBuilder sb) {
        sb.append("## Domain Model\n\n");

        List<DomainType> aggregates = ir.domain().aggregateRoots();
        if (!aggregates.isEmpty()) {
            sb.append("### Aggregate Roots\n\n");
            sb.append("| Name | Package | Properties |\n");
            sb.append("|------|---------|------------|\n");
            for (DomainType agg : aggregates) {
                sb.append("| **")
                        .append(agg.simpleName())
                        .append("** | `")
                        .append(agg.packageName())
                        .append("` | ")
                        .append(agg.properties().size())
                        .append(" |\n");
            }
            sb.append("\n");
        }

        List<DomainType> valueObjects = ir.domain().valueObjects();
        if (!valueObjects.isEmpty()) {
            sb.append("### Value Objects\n\n");
            sb.append("| Name | Package | Type |\n");
            sb.append("|------|---------|------|\n");
            for (DomainType vo : valueObjects) {
                sb.append("| ")
                        .append(vo.simpleName())
                        .append(" | `")
                        .append(vo.packageName())
                        .append("` | ")
                        .append(vo.construct())
                        .append(" |\n");
            }
            sb.append("\n");
        }

        sb.append("*See [domain.md](domain.md) for complete details.*\n\n");
    }

    private void generatePortsSummary(StringBuilder sb) {
        sb.append("## Ports\n\n");

        List<Port> driving = ir.ports().drivingPorts();
        if (!driving.isEmpty()) {
            sb.append("### Driving Ports (Primary)\n\n");
            sb.append("| Port | Kind | Methods |\n");
            sb.append("|------|------|--------|\n");
            for (Port port : driving) {
                sb.append("| **")
                        .append(port.simpleName())
                        .append("** | ")
                        .append(port.kind())
                        .append(" | ")
                        .append(port.methods().size())
                        .append(" |\n");
            }
            sb.append("\n");
        }

        List<Port> driven = ir.ports().drivenPorts();
        if (!driven.isEmpty()) {
            sb.append("### Driven Ports (Secondary)\n\n");
            sb.append("| Port | Kind | Methods |\n");
            sb.append("|------|------|--------|\n");
            for (Port port : driven) {
                sb.append("| **")
                        .append(port.simpleName())
                        .append("** | ")
                        .append(port.kind())
                        .append(" | ")
                        .append(port.methods().size())
                        .append(" |\n");
            }
            sb.append("\n");
        }

        sb.append("*See [ports.md](ports.md) for complete details.*\n\n");
    }

    private String sanitizeId(String name) {
        return name.replaceAll("[^a-zA-Z0-9]", "_");
    }
}
