/*
 * Verify script for hexagonal-architecture-java-springboot integration test.
 * Validates that the audit plugin executed correctly on a full hexagonal architecture project.
 */

def buildLog = new File(basedir, "build.log")
assert buildLog.exists() : "build.log should exist"

def logContent = buildLog.text

// Verify build success
assert !logContent.contains("BUILD FAILURE") : "Build should not fail"

// Verify HexaGlue plugin executed
assert logContent.contains("HexaGlue analyzing:") :
    "Should contain HexaGlue analyzing output"

// Verify classification completed
assert logContent.contains("Classification complete:") :
    "Should contain 'Classification complete:'"

// Check generated sources directory
def generatedSources = new File(basedir, "target/generated-sources/hexaglue")
assert generatedSources.exists() :
    "Generated sources directory should exist"

// Check living-doc directory (generated by default with GENERATOR category)
def livingDocDir = new File(basedir, "target/hexaglue/reports/living-doc")
assert livingDocDir.exists() :
    "Living documentation directory should exist at target/hexaglue/reports/living-doc"

// Verify JPA plugin ran and generated adapters
assert logContent.contains("io.hexaglue.plugin.jpa") :
    "Build log should contain JPA plugin execution"

// Verify JPA generation completed
assert logContent.contains("JPA generation complete:") :
    "Build log should contain JPA generation completion message"

// For hexagonal architecture project, verify ports were detected
assert logContent =~ /\d+ ports/ :
    "Should detect ports in hexagonal architecture project"

println "SUCCESS: sample-starwars integration test passed - JPA plugin generated adapters correctly"
return true
